<?php 
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');
$captchanew = new Zend_Session_Namespace('captchanew');
    $captchanew->captchanew = session_id();
?>

<script type="text/javascript" language="javascript">
			function valPwd2()
			{
				if(document.frm_change.newpassword.value==''||document.frm_change.newpassword.value==null)
				{
					alert("New Password field <?php echo CANTEMPTY; ?>!");
					document.frm_change.newpassword.focus();
					return false;
				}
				if(document.frm_change.newpassword.value.length<8)
				{
					alert("New Password field will take minimum 8 characters!");
					document.frm_change.newpassword.focus();
					return false;
				}
				if(document.frm_change.conpass.value==''||document.frm_change.conpass.value==null)
				{
					alert("Confirm Password field <?php echo CANTEMPTY; ?>!");
					document.frm_change.conpass.focus();
					return false;
				}
				if(document.frm_change.conpass.value.length<8)
				{
					alert("Confirm Password field will take minimum 8 characters!");
					document.frm_change.conpass.focus();
					return false;
				}
				if(document.frm_change.newpassword.value != document.frm_change.conpass.value)
				{
					alert("Confirm Password field not match with the new password field please try again!");
					document.frm_change.conpass.focus();
					return false;
				}
				if(document.frm_change.vercodene.value==''||document.frm_change.vercodene.value==null)
				{
					alert("Captcha code <?php echo CANTEMPTY; ?>");
					document.frm_change.vercodene.focus();
					return false;
				}
				return true;
			}
		</script>

<div class="login-form">
<div class="panel panel-primary">
<div class="panel-heading"><strong>Reset Password</strong></div>
<div class="panel-body">

               
                
                        	<?php $postUrlUpdate = $this->url(array('controller' => 'forgot', 'action'  => 'resetpassword')).'?userid='.$this->userid."&login_temp=".$this->login_temp; ?>
                        <?php 
                        $messing='';
                        if(@$_GET['message']=="sent")
                        {
                            $messing="Password has been sent to your email Id.";
                        }
                        if($messing){?>	
                            <div class="success-msg"> <?php echo $messing; ?></div>
                        <?php }
                        if($this->msg){ ?><div class="form-item"><span class="error-msg"><?php echo $this->escape($this->msg);?></span></div><?php }?>
		              <?php $postUrl = $this->url(array('controller' => 'forgot', 'action'  => 'forgot')); ?>
                        
                   <form action="<?php echo $postUrlUpdate;?>" method="post" name="frm_change" id="login-form" onsubmit="return valPwd2();" class="webform-client-form">
                      
                            <div class="form-group">
<div class="input-group">
<span class="input-group-addon"><i class="glyphicon glyphicon-lock" aria-hidden="true"></i></span>
                               
                              	<?php echo $this->form->newpassword; ?>
                           </div>
                           <span class="require" id="passwords"></span>
                           </div>
							  
							
							   
                            <div class="form-group">
<div class="input-group">
<span class="input-group-addon"><i class="glyphicon glyphicon-lock" aria-hidden="true"></i></span>
                              
                              	<?php echo $this->form->conpass; ?>
                            </div>
                           <span class="require" id="passwords"></span>
                           </div>
                     

		     <!-----------Add Captcha Code Script----->
			 <div class="form-group captcha">
             <?php echo $this->form->vercodene; ?>
               <p>
			   <span><img src="<?php echo $this->baseUrl("cool_capcha/captcha.php"); ?>" id="captcha" class="pull-left" width="248" height="40" /></span>
			 <a  onclick="document.getElementById('captcha').src='/cool_capcha/captcha.php?'+Math.random();
    document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl(); ?>/images/refress.png" class ="refresh" id="refresh" /></a>									
				</p>
			<div class="clearfix"></div><span class="require" id="captcha-code"></span>
			   <input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
           </div> 
           <!--------------End Captcha Code------->						
							
							
                             <div class="form-group">
				<!--<input type="hidden" name="csrf" value="<?php //echo $this->key; ?>" />-->
                                <input id="Submit1" type="submit" class="btn submit-login btn-block" value="Sign In" name="submit" />
                                <!--<input type="submit" value="Log in">-->
                            </div>
                     
                        </form>    
     </div>
</div>
</div>