<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title><?php echo WEBSITE_TITLE;?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		
		
		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/style.css'); ?>">
		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/print.css'); ?>" media="print">
		<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
		<script type="text/javascript" src="<?=$this->baseUrl('js/jquery.min.js') ?>"></script>
		<script type="text/javascript" src="<?=$this->baseUrl('js/jquery.passwordstrength.js') ?>"></script>
		<script type="text/javascript" src="<?=$this->baseUrl('js/application.js') ?>"></script>

		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/style1.css'); ?>" media="screen" />
		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/font-awesome.css'); ?>" media="screen" />


		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<script type="text/javascript" language="javascript">
			function validate()
			{
				 if(document.frm_login.username.value==''||document.frm_login.username.value==null)
			   {
				   alert("Username field cannot be empty");
				   document.frm_login.username.focus();
				   return false;
			   }
				return true;
			}
		</script>



	</head>
	<body>
            
	<div class="cntnr dcWrap">
		<header id="header" class="tlc">
			<div class="toc logo">
				<h1><a href="<?php echo $this->baseUrl();?>" title="<?php echo WEBSITE_TITLE;?>"><img src="<?php echo $this->baseUrl('images/logo.gif');?>" alt="<?php echo WEBSITE_TITLE;?>" /></a></h1>
			</div>
			
		</header>
		<div class="tlc banner">
			<ul class="rslides" id="slider">
				<li><img src="<?php echo $this->baseUrl('images/bannerImg1.jpg');?>" alt="Velocis"><p class="caption"><span class="xxl">Build</span> <span class="lead">a Stable</span> <span class="xl">Network</span><br />Data Center Management</p></li>
				<li><img src="<?php echo $this->baseUrl('images/bannerImg2.jpg');?>" alt="Velocis"><p class="caption"><span class="xxl">Build</span> <span class="lead">a Stable</span> <span class="xl">Network</span><br />Data Center Management</li>
				<li><img src="<?php echo $this->baseUrl('images/bannerImg3.jpg');?>" alt="Velocis"><p class="caption"><span class="xxl">Build</span> <span class="lead">a Stable</span> <span class="xl">Network</span><br />Data Center Management</p></li>
			</ul>
		</div>
		<div class="tlc">
			<? $postUrlUpdate = $this->url(array('controller' => 'forgot', 'action'  => 'resetpassword')); ?>
			<div id="left" class="thc">
				
			</div>
			
			<div class="nnc">
				<h2>Reset Password</h2>
				<div><?php
					if($this->notEqual){
						echo $this->notEqual;
					}else if($this->charmin){
						echo $this->charmin;
					}
					?>
				</div>
				<form action="<?php echo $postUrlUpdate;?>" method="post" name="frm_change" id="frm_change" onsubmit="return valPwd2();" class="webform-client-form">

					<div class="form-item">
						<label>New Password:</label>
						<?=$this->form->newpassword?>
					</div>

					<div class="form-item">
						<label>Confirm Password:</label>
						<?=$this->form->conformnewpassword?>
					</div>
				
				<?=$this->form->ranNumber?>
				<?=$this->form->userencode?>
				
								
					<div  class="form-item">
						<input type="submit" class="mlft" value="Change Password" name="Submit" border="0"  />
						
					</div>
				</form>
			</div>
			
		</div>
		<footer class="tlc">
			<p class="copy"><?php echo COPYRIGHT; ?></p>
		</footer>
		<div class="clr"></div>
	</div>	
	<script src="<?php echo $this->baseUrl('js/jquery.min.js');?>"></script>
	<script src="<?php echo $this->baseUrl('js/responsiveslides.min.js');?>"></script>
	<script>
		$(function () {
			$("#slider").responsiveSlides({
			auto: true,
			pager: true,
			speed: 300,
			//maxwidth: 540
			});
		});
	</script>
</body>
</html>