<?php
$searchUrl = $this->url(array(
    'controller' => 'export',
    'action'  => 'showstate'
    )); 
?>
<form  class="form-inline webform-client-form" role="form" method="post" accept-charset="UTF-8" action="<?=$postUrl?>">
	<div class='table table-responsive'>
		<table class='table' summary='Display the ministry record'>
			<thead>
			<tr>
				<th scope='col'>#</th>
				<th scope='col'>State Name</th>
				<th scope='col'>State Code</th>
			</tr>
			</thead>
			<tbody>
				<?php 
					$data = $this->statearr;
					$i = 1;
					foreach($data as $key => $val){?>
						<tr>
							<td><?php echo $i; ?></td>
							<td><?php echo $val['state_name']; ?></td>
							<td><?php echo $val['state_code']; ?></td>
						</tr>
					<?php
					$i+=1;
					}
				?>
			</tbody>
</form>
<?php
exit;
?>