<?php 
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');
$captchanew = new Zend_Session_Namespace('captchanew');
    $captchanew->captchanew = session_id();
?>

<script type="text/javascript" language="javascript">
jQuery(document).ready(function(){
	

        jQuery("#omadd").submit(function(){
		var alphabetReg = /^[a-zA-Z-. ]*$/;
		var numberReg = /^[0-9]*$/;
                var type =  jQuery("#type").val();
		if (jQuery("#title").val() == '') {
			alert("Title <?php echo CANTEMPTY; ?>");
			jQuery( "#title" ).focus();
			return false;
		}
		if(!alphabetReg.test(jQuery("#title").val())) {
			alert("Invalid title");
			jQuery( "#title" ).focus();
			return false;
		}
		if(!numberReg.test(jQuery("#sort_order").val())) {
			alert("Sort Order field will only accept numeric value");
			jQuery( "#sort_order" ).focus();
			return false;
		}
		if (jQuery("#category").val() == '') {
				alert("Please select a category");
				jQuery( "#category" ).focus();
				return false;
			}
		
			if (jQuery("#uploadfile").val() == '') {
				alert("Upload file <?php echo CANTEMPTY; ?>");
				jQuery( "#uploadfile" ).focus();
				return false;
			}
			if((jQuery("#uploadfile").val() != '')) {
				var file_size = $('#uploadfile')[0].files[0].size;//alert(file_size);
				if(file_size>10485760) {
					alert("File size is greater than 10MB");
					jQuery( "#uploadfile" ).focus();
					return false;
				} 
			}
			
			var ext = $('#uploadfile').val().split('.').pop().toLowerCase();
			if($.inArray(ext, ['doc','DOC','docx','DOCX','pdf','PDF']) == -1) {
			alert('Invalid file extension!');
			jQuery( "#uploadfile" ).focus();
			return false;
			}

                /**************/
                
		if(jQuery('#vercode').val() == '')
		{
			alert("Captcha code <?php echo CANTEMPTY; ?>");
			jQuery( "#vercode" ).focus();
			return false;
		} 
	});
	 function removeSpacesnew(string){
                    return string.split(' ').join('');
                  }
				  
				  
		/// getting OM sub category name from category ajax call.......
	jQuery("#category").change(function(){
	var omcategory = $(this).val();

		//alert("statename_id="+statename_id);
		jQuery.ajax({
			type: "POST",
			url: "../contentmanagement/getomsubcategory?omcategory="+omcategory,
			data: { omcategory: omcategory}
			})
			.done(function( msg ) {
			//alert("MSG"+msg);
			jQuery('#sub_category option').remove();
			jQuery('#sub_category').append(msg);
			 // jQuery("#sub_category").html(msg);
		});
		
	});		  
	
	jQuery( "#filedate" ).datepicker({changeMonth: true,
	changeYear: true});
	
});
</script>

<h2 class="btn btn-block btn-danger margin_bottom10 col-sm-12"><?php echo ADDDOCUMENT; ?></h2>
<?php $postUrl = $this->url(array(
                'controller' => 'contentmanagement',
                //'action'  => 'userview'
                )); ?>
<form role="form" method="post" enctype="multipart/form-data"  action="<?php echo $postUrl; ?>" name="frmAddGallery" id="omadd">
					
        <?php if($this->errorMessage){?>
			<div class='error-msg'><span class="errors"><?php echo $this->errorMessage; ?></span></div>
		<?php } ?>
		<?php if($this->successMsg){?>
			<div class='success-msg'><span class="errors"><?php echo $this->successMsg; ?></span></div>
		<?php } ?>
        <div class="row">
            <div class="form-group col-sm-6">
                <label>Title<sup class="require">*</sup> </label>
                <?php echo $this->form->title; ?>
            </div>	
            <div class="form-group col-sm-6">
                <label>File Number</label>
                <?php echo $this->form->filenumber; ?>
            </div>	
            <div class="form-group col-sm-6">
                <label>File Date</label>
                <?php echo $this->form->filedate; ?>
            </div>	
             <div class="form-group col-sm-6">
                <label>Sort Order</label>
                <?php echo $this->form->sort_order; ?>
            </div>	
            <div class="form-group col-sm-6">
                <label>Language<sup class="require">*</sup> </label>
                <?php echo $this->form->language; ?>
            </div>
			   <div class="form-group col-sm-6">
                <label>Category<sup class="require">*</sup> </label>
                <?php echo $this->form->category; ?>
            </div>
			 <div class="form-group col-sm-6">
                <label>Sub Category</label>
                <?php echo $this->form->sub_category; ?>
            </div><br/>
			
			 <div class="form-group col-sm-6" id="upload_image">
                <label><span id="label_upload_file">Upload File(only pdf,doc,docx file are allowed.Max size- 10MB)</span><sup class="require">*</sup> </label>
                <?php echo $this->form->uploadfile; ?>
            </div>
			<!-----------Add Captcha Code Script----->
			<div class="form-group col-sm-4">
				<label>Captcha Code<sup class="require">*</sup>  </label>
				<p>
					<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left"/>
					<span><a  onclick="
						document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();
						document.getElementById('vercode').focus();"
						id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>
					</span>									
				</p>
				<p class="text-left">										
					<?php echo $this->form->vercode; ?>
				</p>
				<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
            </div>
           <!--------------End Captcha Code------->			
			<div class="form-group col-md-12 col-sm-12 text-center">
				<button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="addGalleryButton">Submit</button>
                <button type="reset" class="btn active text-center" id="cancleGalleryButton"><?php echo CANCEL; ?></button>
            </div>
        </div>
        
</form>

