<?php 
//echo "sdsdsdsdsdsdsdsdsdsdsd";exit;
//echo $this->search;
//echo $_GET['type'];
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');
$captchanew = new Zend_Session_Namespace('captchanew');
 $captchanew->captchanew = session_id();
$transferengineer=$this->transferengineer;
$searchUrl = $this->url(array(
            'controller' => 'contentmanagement',
            'action'  => 'omview'
            ));
	$array_content_type = array('1'=> 'Header Menu Content', '2'=> 'Footer Menu Content', '3'=> 'Other Content');
	//print_r($array_content_type);
?>
<script type="text/javascript" language="javascript">
jQuery(document).ready(function(){
	jQuery(".rstbtn").click(function(){
		
		jQuery(".srch-box").val('');
		window.location.href="<?php echo $searchUrl; ?>";
	});
});
</script>
<h2>Document Management</h2>
<div class="cntnt">
    <?php
        $omdata = $this->omdata;//print"<pre>";print_r($omdata);die;
        $Count = $this->counttotalcmireports;
        $language = $this->language;
	
        if($this->successMsg){
            echo "<div class='success-msg'>".$this->successMsg."</div>"; 
        }
    ?>
   
	  <div class="data-found">
		
		<div class="filterData">
                    <div class="col-sm-12 col-md-7">
                        <div class="row">
                            <form method="get" class="form-inline" action="<?=$searchUrl.'?search='.$searchUrl?>">
				<label><?php echo SEARCH_BY; ?></label>

					<input type="text" name="title" class="form-control" placeholder="Document title, Category"/>

				<input class="rolBtn  btn btn-default btn-warning text-center" type="Submit" name="Submit" value="Search"/>
				<input class="rolBtn rstbtn btn active text-center" type="reset" name="reset" value="Reset"/> 
			</form>
                </div></div>
 <div class="col-sm-12 col-md-5 text-right">
			<?php if($role->role==1){ ?>
			<a class="btn btn-warning pull-right margin-right-15" href="<?php echo $this->baseUrl(); ?>/contentmanagement/omadd" title="<?php echo Upload_Document; ?>"><?php echo Upload_Document; ?></a>


			<?php }else if((($transferengineer)!= "")&&($role->role==4)){ ?>
			<a class="btn btn-warning pull-right margin-right-15" href="<?php echo $this->baseUrl(); ?>/contentmanagement/omadd" title="<?php echo Upload_Document; ?>"><?php echo Upload_Document; ?></a>
			<?php } ?>
		</div>
        <div class="col-sm-12 col-xs-6 text-center record_box">
		   <?php if($Count): echo '<span>'.$Count ." ".RECORD_FOUND.'</span>'; endif;?></div>
    </div>
	
    <?php $postUrl = $this->url(array(
            'controller' => 'contentmanagement',
            'action'  => 'ominactive'
            ));
        ?>
     <form  class="form-inline webform-client-form" role="form" method="post" accept-charset="UTF-8" action="<?=$postUrl?>">
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>S. No.</th>
                    <th>Document name</th>
                    <th>Category</th>
                    <th>Sub category</th>
                    <th>Language</th>					
                    <th>Status</th>
                    <th>Edit</th>
                    <!--<th>Delete</th>-->
                </tr>
            </thead>
            <tbody><?php if($Count ==0)
                    { ?>
                        <tr>
                            <td colspan="8"><?php echo RECORD_EMPTY;?></td>
                        </tr>
                    <?php
                    }else{
                        $i=1;//
                        foreach ($omdata as $key => $val)
                        {
							//print_r($val);
						?>
						<tr>
						<td><input type="checkbox" name="roleid[<?php echo $val['id'];?>]" id="roleid"></td>
						 <td><?php echo $i+$this->start;?></td>
						 
                         <td><?php 
						echo $this->escape($val['title']);
						?></td>
						<td><?php 
						echo $this->escape($val['category']);
						?></td>
						<td><?php 
						echo $this->escape($val['subcategory']);
						?></td>
					    <td><?php echo $this->escape($val['langname']);
						
						?></td>
						 <td> <?php  echo ($this->escape($val['status']==1))?"Active":"Inactive";?></td>
                                    <?php $cmiurl = $this->url(array(
                                         'controller' => 'contentmanagement',
                                         'action' => 'omedit'
                                        ))."?id=".$this->escape($val['id']);
										
										
                                    ?>
                                <td> <a href="<?php echo $cmiurl;?>" class="menu1">Edit</a></td>
						
						
						</tr>
                            
                            <?php ++$i;
                        }
                    }?>
                </tbody> 
        </table>
        <div class="status">
            <select name="status" class="form-control" id="statusId">
                <option value="1">Active</option>
                <option value="0">Inactive</option>
            </select>
	     <input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
             <button class="btn btn-default btn-warning text-center rolBtn" type="Submit" name="Submit">Submit</button>
           <!-- <input class="rolBtn" type="Submit" name="Submit" value="Submit"/>-->
        </div>
    </form>
    <?php echo $this->paginate; ?>
</div>
		
