<?php 
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');
$captchanew = new Zend_Session_Namespace('captchanew');
    $captchanew->captchanew = session_id();
$transferengineer=$this->transferengineer;
$searchUrl = $this->url(array(
            'controller' => 'scheme',
            'action'  => 'schemeview'
            )); 
?>
<script type="text/javascript" language="javascript">
jQuery(document).ready(function(){
	jQuery(".rstbtn").click(function(){
		
		jQuery(".srch-box").val('');
		window.location.href="<?php echo $searchUrl; ?>";
	});
});
function atleast_onecheckbox(e) {
  if ($("input[type=checkbox]:checked").length === 0) {
      e.preventDefault();
     $('#error-msgdone').html("Please choose atleast one scheme.");
      return false;
  }
 
}
</script>


<ol class="breadcrumb">
   <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
   <li class="active">Scheme List</li>
</ol>

<h2>Scheme Details<a class="pull-right" href="<?php echo $this->baseUrl('/samplecsv/DBT_App_User_Manual_Manage_Scheme_V3.pdf'); ?>"  target="_blank">Help?</a> </h2>
<div class="cntnt">
    <?php
        $cmidata = $this->cmidata;
        //echo "<pre>";
       // print_r($cmidata);exit;
        $Count = $this->counttotalcmireports;
   
        if($this->successMsg){
            echo "<div class='success-msg'>".$this->successMsg."</div>"; 
        }
		if(isset($_GET['status']) && $_GET['status']=='updated'){
			echo "<div class='success-msg'>Scheme data was successfully updated.</div>"; 
			}
    ?>
   <div class="row">
	  <div class="col-sm-12">
			<form class="form-inline" role="form" method="get" action="<?=$searchUrl.'?search='.$searchUrl?>">
				<div class="row">
                	<div class="col-md-9 col-sm-12">
                    <div class="form-group margin-left-15">
                        <label><?php echo SEARCH_BY; ?></label>
                        <input class="form-control" type="text" placeholder="Scheme or Ministry" name="search" value="<?=safexss($this->escape(@$_GET['search']))?>">
                   		<button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Submit</button>
                <button type="reset" class="btn active text-center" name="reset" id="sechemSearchButton">Cancel</button>
                        <!--<input class="rolBtn" type="Submit" name="Submit" value="Search"/>
                        <input class="rolBtn rstbtn" type="reset" name="reset" value="Reset"/> -->
                 </div>
                </div>
               
                	<div class="col-md-3 col-sm-12 text-right">
                <?php if($role->role==1 || $role->role==6){ ?>
			
           <a class="btn btn-warning margin-right-15" href="<?php echo $this->baseUrl(); ?>/scheme" title="<?php echo ADD_NEW_LOCATION; ?>"><?php echo ADD_NEW_LOCATION; ?></a>
			<?php } ?>
                
                </div>
                </div>
			</form>

<div class='row'><div class="col-sm-12 text-center record_box">
 <?php if($Count): echo '<span>'.$Count ." ".RECORD_FOUND.'</span>'; endif;?>
    </div>
</div>
	
    <? $postUrl = $this->url(array(
            'controller' => 'scheme',
            'action'  => 'schemeinactive'
            ));
        ?>
        
    <form  class="form-inline" role="form"  method="post" accept-charset="UTF-8" action="<?=$postUrl?>" onsubmit="return atleast_onecheckbox(event)">
	<div class='table table-responsive'>
        <table class='table'>
            <thead>
                <tr>
                    <th>#</th>
                    <th width="5%"><?php echo SNo; ?></th>
					<th>Scheme Code</th>
                    <th>Scheme Name</th>
                    <th>Ministry</th>
                    <!--<th>Scheme Details</th>	-->	
                    <th>Benefit Type</th>	
                  <th>Scheme Type</th>						
                    <th>Status</th>
                    <th>Action</th>
                    <!--<th>Delete</th>-->
                </tr>
            </thead>
            <tbody><?php if($Count==0)
                    { ?>
                        <tr>
                            <td colspan="10" class='text-center'><?php echo RECORD_EMPTY;?></td>
                        </tr>
                    <?php
                    }else{
                        $i=1;
                        foreach ($cmidata as $key => $val)
                        { ?>
                            <tr>
                                <td><input type="checkbox" name="roleid[<?php echo $val['id'];?>]" id="roleid"></td>
								
                                <td><?php echo $i+$this->start;?></td>
								 
								 <td> <?php echo $this->escape($val['scheme_codification']);?></td>
								 
                                <td> <?php echo $this->escape($val['scheme_name']);?></td>
                                <td> <?php echo $this->escape($val['ministryname']);?></td>
                                <!--<td><?php //echo $val['description'];?></td>-->
                                <?php 

                                 if($this->escape($val['scheme_type']) == "1"){
                                    echo "<td> In Cash </td>";
                                }else if($this->escape($val['scheme_type']) == "2"){
                                    echo "<td> In Kind </td>";
                                }else if($this->escape($val['scheme_type']) == "3"){
                                    echo "<td> In Others </td>";
                                }else{
                                    echo "<td> ---- </td>";
                                }
                                ?>
								 <?php 

                                 if($this->escape($val['scheme_group']) == "1"){
                                    echo "<td> Central Sector Scheme </td>";
                                }else if($this->escape($val['scheme_group']) == "2"){
                                    echo "<td> State/UTs Scheme </td>";
                                }else if($this->escape($val['scheme_group']) == "3"){
                                    echo "<td> Centrally Sponsored Scheme </td>";
                                }else if($this->escape($val['scheme_group']) == "4"){
                                    echo "<td> District Scheme </td>";
                                }else if($this->escape($val['scheme_group']) == "5" || ($this->escape($val['scheme_group']) == "")){
                                    echo "<td> OTHERS </td>";
                                }else{
                                    echo "<td> ---- </td>";
                                }
                                ?>
                                <td> <?php echo ($this->escape($val['status']==1))?"Active":"Inactive";?></td>
                                    <?php $cmiurl = $this->url(array(
                                         'controller' => 'scheme',
                                         'action' => 'schemeedit'
                                        ))."?id=".safexss(base64_encode($this->escape($val['id']))); 
										
										
										$cmiurlTranslateold = $this->url(array(
                                         'controller' => 'scheme',
                                         'action' => 'schemetranslate'
                                        ))."?id=".$this->escape($val['id']);
										
										
										$cmiurlTranslatenew = $this->url(array(
                                         'controller' => 'scheme',
                                         'action' => 'schemetranslateedit'
                                        ))."?id=".$this->escape($val['translation_id']); 
                                    ?>
                                <td> <a href="<?php echo $cmiurl;?>" class="menu1">Edit</a> 
								
								<!--<a href="<?php //if($val['translation_id'] == 0) { echo  $cmiurlTranslateold;  } else { echo $cmiurlTranslatenew; }?>" class="menu1">Translate in Hindi</a></td>-->
                              <!--  <td><?php $name= "'".$this->escape($val['scheme_name'])."'"; ?>
                                         <a href="delete/id/<?php echo $this->escape($val['id']); ?>" onclick="return confirm('Are you sure you want to delete this scheme ?');" class="menu1">Delete</a>
                                </td> -->

                            </tr>
                            <?php ++$i;
                        }
                    }?>
                </tbody> 
        </table>
		</div>
		<div>  <span class="require" id="error-msgdone"></span> </div>
        <div class="status">
            <select name="status" class="form-control" id="statusId">
                <option value="1">Active</option>
                <option value="0">Inactive</option>
            </select>
             <input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
           <button class="btn btn-default btn-warning text-center rolBtn" type="Submit"  name="Submit" >Submit</button>
        </div>
    </form>
   <div class="row text-center"> <?php echo $this->paginate; ?></div>
</div>
</div>
		
