
<?php
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');
?>
                          
<script src="//cdn.ckeditor.com/4.5.9/full/ckeditor.js">
</script>

<script>
jQuery(document).ready(function(){
     jQuery("#frmfeedback").submit(function(){
                
                var fname_regex = /^[a-zA-Z]+$/;
				
                    var name = $("#name").val();
			if(name == '' || name == null){
				alert("Name <?php echo CANTEMPTY; ?>");
				$("#name").focus();
				return false;
			}
			else if(!name.match(fname_regex))
			       {
					   alert("Name <?php echo ALPHABETSVALIDATION; ?>");
					   $("#name").focus();
			        	return false;
				   }
		
                var email_regex = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/; 			
		
	        var email = $("#email").val();
			if(email == '' || email == null){
				alert("Email <?php echo CANTEMPTY; ?>");
				$("#email").focus();
				return false;
			}
			else if(!email.match(email_regex))
			       {
					   alert(" <?php echo EMAILVALIDATION; ?>");
					   		$("#email").focus();
				            return false;
				   }
                var mobile_regex = /^[0-9]+$/;
				
                    var mobile = $("#mobile").val();
			if(mobile == '' || mobile == null){
				alert("Mobile <?php echo CANTEMPTY; ?>");
				$("#mobile").focus();
				return false;
			}
			else if(!mobile.match(mobile_regex))
			       {
					   alert("Mobile <?php echo NUMERICVALIDATION; ?>");;
					   $("#mobile").focus();
			        	return false;
			        }
		        else if(mobile.length != '10')
                                   {
                                           alert("Mobile should be of 10 digits");
				           	   $("#mobile").focus();
			                 	return false;
			         	   
                                   } 

                         var details = $("#details").val();
			if(details == '' || details == null){
				alert("Details <?php echo CANTEMPTY; ?>");
				$("#details").focus();
				return false;
			}

                      
                         if($('#type').val() == '0') 
                          {
                                 alert("Type <?php echo CANTEMPTY; ?>");
				
			                 	return false;
			         	  
                          }

    

     });   
 });

</script>



<div class="cntnt">
	<h2 class="margin_left15"><?php echo EDIT_Feedback;?></h2>			
				
					<form  class="webform-client-form" method="post" accept-charset="UTF-8" action="<?=$postUrlUpdate?>" name="frmfeedback" id="frmfeedback" onsubmit="return validate();">
							<?php 
							if($this->errorMessage){
							echo "<div class='error-msg'>".$this->errorMessage."</div>"; 
							}
							?>

			
            
            
            

            <div class="form-group col-sm-6">
                <label>TYPE<sup class="require">*</sup> </label>
                <?php echo $this->form->type;?>
            </div>	
            
             
            <div class="form-group col-sm-6">
                <label>NAME<sup class="require">*</sup> </label>
                <?php echo $this->form->name;?>
            </div>	  
            
            <div class="form-group col-sm-6">
                <label>EMAIL<sup class="require">*</sup> </label>
                <?php echo $this->form->email;?>
                
            </div>	<div class="form-group col-sm-6">
                <label>MOBILE<sup class="require">*</sup> </label>
                <?php echo $this->form->mobile;?>
            </div>	
            
            
            <div class="form-group col-sm-12">
                <label>DETAILS<sup class="require">*</sup> </label>
                <?php echo $this->form->details;?>
            </div>	
            
          	<div class="form-group col-md-12 col-sm-12 text-center">
               <button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Submit</button>
                <button type="reset" class="btn active text-center" id="sechemSearchButton"><?php echo CANCEL; ?></button>
            </div>
           
				</form>
	 </div>


