<?php 
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');
$transferengineer=$this->transferengineer;
$validate_status=base64_decode($_GET['validate_status']);

$schemename= $this->scheme_id;
$cmidata = $this->cmidata;
//echo "aaaa";exit;
//print_r($cmidata);exit;
$min_id = $cmidata[0]['min_id'] != "" ?  base64_encode($cmidata[0]['min_id']) : isset($_GET['min_id']) ? $_GET['min_id']: "";


$paramid = "?scheme_id=".base64_encode($schemename[0]->id)."&min_id=".safexss($_GET['min_id'])."&status=".safexss($_GET['status'])."&scm_type=".safexss($_GET['scm_type']);
$searchUrl = $searchUrl.'?scheme_id='.$schemename[0]->id;
//echo $paramid;exit;
?>
<script type="text/javascript" language="javascript">
$(document).ready(function(){
	$("#sechemSearchCancleButton").click(function(){
		window.location.href="<?php echo $paramid; ?>";
	});
});
//*********************** Aadhar validate by API 1.6 start now************************** 
$(document).ready(function() {
    $("#aadhar_validate_ncpi").click(function() {
		
	$.ajaxSetup({
                    global: false,
                    type: "GET",
                    url: "https://api.ipify.org?format=json",
                    beforeSend: function () {
                        $(".screenback").css({'display':'block','z-index':'100'});
                    },
                    complete: function () {
                        $(".screenback").css({'display':'none','z-index':'100'});;
                    }
                });
       $.ajax({
			type:"POST",
			url:"<?php echo $this->baseUrl('aadharvalidateapi/validateaadhar');?>"+"<?php echo $paramid;?>",
			success:function(response){
				
				if(response==1){
//alert("jkwedw");
				window.location.href="<?php echo $this->baseUrl('schemeowner/aadharvalidate?');?>"+"<?php echo $paramid;?>"+"&status=2";
			}else{
//alert(response);
				window.location.href="<?php echo $this->baseUrl('schemeowner/beneficiarydatalist?');?>"+response;
				}
				
		}
		}); 
    });
});

$(document).ready(function() {
    $("#aadhar_validate_uidai").click(function() {
	
	$.ajaxSetup({
                    global: false,
                    type: "GET",
                    url: "https://api.ipify.org?format=json",
                    beforeSend: function () {
                        $(".screenback").css({'display':'block','z-index':'100'});
                    },
                    complete: function () {
                        $(".screenback").css({'display':'none','z-index':'100'});;
                    }
                });
			//alert("whjedwegd");
       $.ajax({
			type:"POST",
			url:"<?php echo $this->baseUrl('aadharvalidateapi/validateaadharbyuidai');?>"+"<?php echo $paramid;?>",
			success:function(response){
				//alert(response);
				if(response==1){
				window.location.href="<?php echo $this->baseUrl('schemeowner/aadharvalidate?');?>"+"<?php echo $paramid;?>"+"&status=1";
			}else{
				window.location.href="<?php echo $this->baseUrl('schemeowner/aadharvalidate?');?>"+response;
				}
				
		}
		}); 
    });
});
//*********************** Aadhar validate by API 1.6 end now***************************
</script>
<!--- ************************************************* --->

<ol class="breadcrumb">
   <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
   <li><a href="<?php echo $this->baseUrl('schemeowner/schemeview'); ?>">Scheme List</a></li>
   <li><a href="<?php echo $this->baseUrl('schemeowner/beneficiarydatalist'.$paramid); ?>">Beneficiaries Record</a></li>
   <li class="active">Validate Aadhaar Number</li>
</ol>
<div class="row">
<div class="col-sm-9 col-xs-12"><h2><?php $schemename= $this->scheme_id; 
if(isset($_GET['scm_type']) && base64_decode($_GET['scm_type']) == 1){
			$type = " (In Cash)";
		}else if(isset($_GET['scm_type']) && base64_decode($_GET['scm_type']) == 2){
			$type = " (In Kind)";
		}else if(isset($_GET['scm_type']) && base64_decode($_GET['scm_type']) == 3){
			$type = " (In Others)";
		}else{
			$type = "";
		}
echo "Scheme Name : ".$schemename[0]->scheme_name.$type."&nbsp;&nbsp; Scheme Code: ".$this->scheme_code[0]['scheme_codification'];
?>  </h2> </div>
<div class="col-sm-3 col-xs-12 text-right"><a href="<?php echo $this->baseUrl('/samplecsv/DBT-Schemes-Management-User-Manual-Manage-Beneficiary-v1.pdf'); ?>"  target="_blank">Help?</a></div></div>

<!--- ************************************************* --->
<!--  ************** Loader div start now *******************-->
<div class="screenback" style="display: none">
<div class="loader text-center">
       
            <!--<img alt="" src="<?php //echo $this->baseUrl('images/loader.gif');?>"/>-->
       
    </div></div>
<!--  ************** Loader div start end *******************-->
   <div class="row">
	  <div class="col-sm-12">
	
 
<?php
//echo "<pre>";print_r($this->cmidata);echo "</pre>";die;
        $cmidata = $this->cmidata;
        $Count = $this->counttotalcmireports;
	   $min_id = $min_id;
	   //echo $min_id;exit;
        $cmidata = $this->cmidata;
        $Count = $this->counttotalcmireports;
	//echo base64_decode($_GET['existval']);
        if($this->successMsg){
            echo "<div class='success-msg'>".$this->successMsg."</div>"; 
        }
		if(isset($_GET['existval']) && base64_decode($_GET['existval']) > 0){
            echo "<div class='error-msg'>".base64_decode($_GET['existval']) ." record(s) Aadhaar number has already taken.</div>"; 
        }
		if(isset($_GET['ntsv']) && base64_decode($_GET['ntsv']) > 0){
            echo "<div class='error-msg'>".base64_decode($_GET['ntsv']) ." record(s) was not save because of the wrong Aadhaar Number.</div>"; 
        }
		if(isset($_GET['lenad']) && base64_decode($_GET['lenad']) > 0){
            echo "<div class='error-msg'>".base64_decode($_GET['lenad']) ." record(s) was not save because of the wrong Aadhaar Number length.</div>"; 
        }
		if(isset($_GET['aadhar_status_false']) && base64_decode($_GET['aadhar_status_false'])>0){
            echo "<div class='error-msg'>".base64_decode($_GET['aadhar_status_false']).' '.AADHAR_UIDAI_FAIL."</div>"; 
        }
		if(isset($_GET['aadhar_status']) && base64_decode($_GET['aadhar_status'])>0){
            echo "<div class='success-msg'>".base64_decode($_GET['aadhar_status']).' '.AADHAR_UIDAI_SUCCESS."</div>"; 
        }
		if(isset($_GET['status']) && $_GET['status'] > 0){
            echo "<div class='error-msg'>Show thing wrong happen!!</div>"; 
        }
		
?>
		
		<div class="row"><div class="col-sm-12">
			<?php 
			//below initialization using exporting filter wise data
			$to = $from = $benef_id = $st = $dt = $bl = $vi = null;
			if(isset($_GET['benef_id'])){
				$benef_id = $_GET['benef_id'];
			}
			if(isset($_GET['name'])){
				$name = $_GET['name'];
			}
			if(isset($_GET['dob'])){
				$dob = $_GET['dob'];
			}
			$paramtobeexp = "&benef_id=".$benef_id."&name=".$name."&dob=".$dob;

			?>

			
          
		<div class="row"><div class="col-sm-12 text-center record_box">
			<?php if($Count): echo $Count ." ".RECORD_FOUND; endif;?>
			<?php if(!$Count): echo 0 ." ".RECORD_FOUND; endif;?>
		</div>
		</div>

		
		<?php $postUrl = $this->url(array(
                'controller' => 'schememanualdata',
                'action'  => 'schememanualdatainactive'
            )); 
        ?> 
		
		
		
        <div class="table table-responsive">
		<table class="table" summary="schemes name">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col"><?php echo SNo; ?></th>
					<!--<th scope="col">Scheme Type</th>-->
					<th scope="col">Name</th>
                    <th scope="col">Unique ID</th>
                    <th scope="col">Email ID</th>
					<th scope="col">Aadhaar Number</th>
					<th scope="col">Seeded with aadhar Status</th>
                </tr>
            </thead>
			 <tbody>
	<?php if($Count==0){ ?>
			<tr>
				<td colspan="12" class="text-center"><?php echo RECORD_EMPTY;?></td>
			</tr><?php
		}else{
            $i=1;
			$month_val = array('01' => 'January', '02' => 'February', '03' => 'March', '04' => 'April', '05' => 'May', '06' => 'June', '07' => 'July', '08' => 'August', '09' => 'September', '10' => 'October', '11' => 'November', '12' => 'December');
            foreach ($cmidata as $key => $val){
		
		?>
        <tr>
		<td><input type="checkbox" checked="checked" name="roleid[<?php echo $this->escape($val['id']);?>" id="schemeid" disabled></td>
		<td><?php echo $i+$this->start;?></td>
		
		
		
		<td><?php echo $this->escape($val['name']);?></td>
		<td><?php echo $this->escape($val['uniq_user_id']);?></td>
		<td><?php echo $this->escape($val['email_id']);?></td>
		<td><?php
			echo $this->escape($val['aadhar_num']);?>
		</td>
		<td><?php
			echo $this->escape($val['aadhar_seeded']);?>
		</td>
		<?php 
			$par = "?id=".base64_encode($this->escape($val['id']))."&scheme_id=".base64_encode($this->escape($schemename[0]->id))."&uuid=".base64_encode($val['uniq_user_id'])."&scmtype=".base64_encode($this->escape($val['scheme_type']))."&min_id=".$_GET['min_id']."&status=".$_GET['status'];
        ?>
		
		</tr>
		<?php ++$i;
		}
		}?>
		</tbody> 
			</table><br/>
<?php  if($Count>0){ ?>
<div class="text-center" align="justify;">
<button class="btn btn-warning" href="javascript:void(0);"  id="aadhar_validate_uidai" title="Aadhaar  validation by UIDAI – Demo Authentication" <?php //if(isset($validate_status) && $validate_status!=1){ echo "disabled";}?>>Aadhaar  validation by UIDAI – Demo Authentication</button>


<button class="btn btn-warning" href="javascript:void(0);"  id="aadhar_validate_ncpi" title="NPCI validation for Aadhaar linked Bank Account" <?php //if(isset($validate_status) && $validate_status!=2){ echo "disabled";}?>>NPCI validation for Aadhaar linked Bank Account</button>

</div>
<?php  }?>
</div>   
		
<div class="text-center">
<?php
    echo $this->paginate;
    ?>
</div>
		</div>
	</div>


<p>


<section class="container-fluid">
	<div class="row">

	<div class="modal fade" id="conf-pop" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">

	<!-- Modal content-->
	<div class="modal-content">
	<div class="modal-header">
	<h2>Validation</h2>
	</div>
	<div class="modal-body">
    <div>Your beneficiary has been successfully added in the database.<br/><br/> 
			Check mark all the beneficiary is selected- default.<br/><br/>

Now you have to validate these beneficiary’s by following these steps:<br/><br/><h2>Step -1</h2>To validate beneficiary’s personal information with Aadhaar number through Demographic Authentication<br/><br/><h2>Step -2</h2>To validate beneficiary’s bank account seeded with Aadhaar through NPCI Mapper.</div>
	<div class="text-center"><button class="btn btn-primary" data-dismiss="modal">Ok</button></div>
	</div>
	</div>
	</div>
	</div>

	</div>
	</section>
<!--  script for popup ------------->
<script type="text/javascript">
	   $(window).load(function() {
		<?php if(isset($validate_status) && $validate_status==1 && base64_decode($_GET['existval'])==0 && base64_decode($_GET['ntsv'])==0 && base64_decode($_GET['lenad'])==0){?>
		$('#conf-pop').modal('show');
		<?php }?>
	   });
      </script>
