<?php 
//echo "aaaa";exit;
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');

$searchUrl = $this->url(array(
            'controller' => 'schemeowner',
            'action'  => 'schemedatabenlist'
            )); 
$schemename= $this->scheme_id;
$searchUrl = $searchUrl.'?scheme_id='.$schemename[1].'&scheme_name='.$schemename[0];
?>
<script type="text/javascript" language="javascript">
jQuery(document).ready(function(){
	jQuery(".rstbtn").click(function(){
		
		jQuery(".srch-box").val('');
		window.location.href="<?php echo $searchUrl; ?>";
	});
});
</script>
<h2><?php
echo "Scheme Name : ".str_replace("_", " ", strtoupper(base64_decode($schemename[0])));
?></h2> 
<div class="cntnt">
 
<?php
        $cmidata = $this->cmidata;
        $Count = $this->counttotalcmireports;
   
        if(($this->successMsg)|| ($_GET['success']=='success')){
            echo "<div class='success-msg'>Beneficiary has been uploaded successfully.</div>"; 
        }
    ?>

<?php

$month = array( '01' => 'January',
				'02' => 'February',
				'03' => 'March',
				'04' => 'April',
				'05' => 'May',
				'06' => 'June',
				'07' => 'July',
				'08' => 'August',
				'09' => 'September',
				'10' => 'October',
				'12' => 'November',
				'12' => 'December',         
			  );
$currentyear = date('Y');
?>
		<form class="form-inline" method="get" action="<?=$searchUrl.'?search='.$searchUrl?>">
			<div class="col-md-9 col-sm-12">
				<div class="form-group margin-left-15">
					<label><?php echo SEARCH_BY; ?></label>
			<span class="dateinput">
				<select name="month" class="form-control" >
				  <option value="0">Select Month</option>
					<?php 
						$monthval = $_GET['month'];
						foreach ($month as $k => $value) {
							if($k == $monthval){
								echo '<option selected value='.$k.'>'.$value.'</option>';
							} else {
								echo '<option value='.$k.'>'.$value.'</option>';
							}
						}
					?>
				  
				</select>

				<select name="year" class="form-control" >
				  <option value="0">Select Year</option>
					<?php
						$yearvalue = $_GET['year'];
						for($i=$currentyear; $i >= $currentyear - 5; $i--){
							$financialyearfrom = $i;
							$financialyearto = $i;
							$yearval = $financialyearfrom;
							if($yearval == $yearvalue){
								echo '<option selected value='.$yearval.'>'.$yearval.'</option>';
							} else {
								echo '<option value='.$yearval.'>'.$yearval.'</option>';
							}
						}
					?>
				</select>
			</span>
					
				<input class="rolBtn" type="hidden" name="scheme_id" value="<?php echo $schemename[1]; ?>"/>
				<input class="rolBtn" type="hidden" name="scheme_name" value="<?php echo $schemename[0]; ?>"/>
				<!-- <input class="rolBtn" type="Submit" name="Submit" value="Search"/>
				<input class="rolBtn rstbtn" type="reset" name="reset" value="Reset"/> -->
				<button type="Submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Submit</button>
				<button type="reset" class="btn active text-center" name="reset" id="reset">Reset</button>

			</div>
		</div>
<?php if ((base64_decode($schemename[1]) == 1)||(base64_decode($schemename[1]) == 3)||(base64_decode($schemename[1]) == 77)) {?>
					<div class="col-md-3 col-sm-12 text-right">
						<a class="btn btn-warning margin-right-15" href="<?php echo $this->baseUrl(); ?>/schemeowner/importscheme?scheme_id=<?php echo $schemename[1].'&scheme_name='. $schemename[0]; ?>" title="<?php echo 'File upload'; ?>"><?php echo 'File upload'; ?></a>
					</div>
<?php } ?>
		</form>

		<div class="col-sm-12 col-xs-6 text-center record_box">
			<?php if($Count): echo $Count ." ".RECORD_FOUND; endif;?>
			<?php if(!$Count): echo 0 ." ".RECORD_FOUND; endif;?>
		</div>

 <?php $postUrl = $this->url(array(
                'controller' => 'schemeowner',
                //'action'  => 'schemeownerinactive'
            )); 
        ?> 
<form  class="webform-client-form form-inline" method="post" accept-charset="UTF-8" action="<?php echo $postUrl; ?>">
        <table>
            <thead>
                <tr>
                    <th>S. No.</th>
                    <th>Name of State</th>
                    <th>Name of District</th>
                    <th>No. of Transaction with Aadhaar seeded</th>
                    <th>No. of Transaction</th>
                    <th>Total Amount Transferred</th>
                    <th>Fund Transferred</th>
                    <th>Transaction Date</th>
                    <!-- <th>Ration Card no.</th> -->
                    <!-- <th>Amount</th>
                    <th>Fund Transfer</th>
					<th>Village</th>
					<th>Panchayat</th>
					<th>Block</th>	
					<th>District</th>
					<th>State</th> -->
						
						

					
                </tr>
            </thead>
            <tbody><?php if($Count==0){ ?>
                        <tr>
                            <td colspan="16"><?php echo RECORD_EMPTY;?></td>
                        </tr>
                    <?php } else {
                        $i=1;
						$month_val = array('01' => 'Jan', '02' => 'Feb', '03' => 'Mar', '04' => 'Apr', '05' => 'May', '06' => 'Jun', '07' => 'Jul', '08' => 'Aug', '09' => 'Sep', '10' => 'Oct', '11' => 'Nov', '12' => 'Dec');
                        foreach ($cmidata as $key => $val) { 
						?>
                            <tr>
								<td><?php echo $i+$this->start;?></td>
								<td> <?php echo $this->escape(ucfirst($val['state_name']));?></td>
								<td> <?php echo $this->escape(ucfirst($val['district_name']));?></td>
								<td> <?php echo $this->escape($val['amount']);?></td>
								<td> <?php echo $this->escape($val['fund_transfer']);?></td>
								<td> <?php echo $this->escape($val['transaction_date']);?></td>
								
																
                            </tr>
                            <?php ++$i;
                        }
                    }?>
                </tbody> 
        </table>
       
    </form>
<?php
    echo $this->paginate;
    ?>

</div>

