<?php 
    $userid = new Zend_Session_Namespace('userid');
    $unme= $userid->userid;
    $role = new Zend_Session_Namespace('role');
    $captchanew = new Zend_Session_Namespace('captchanew');
    $captchanew->captchanew = session_id();
?>

<script type="text/javascript" language="javascript">
jQuery(document).ready(function()
{
	jQuery("#addMinistry").submit(function()
	{
		if (jQuery("#ministry_name").val() == '')
		 {
			alert("Ministry Name<?php echo CANTEMPTY; ?>");
			jQuery( "#ministry_name" ).focus();
			return false;
		}
		if(jQuery('#vercode').val() == '')
		{
			alert("Captcha code <?php echo CANTEMPTY; ?>");
			jQuery( "#vercode" ).focus();
			return false;
		} 
		
		
	});
});
</script>
<h2><?php echo MINISTRY_IN_HINDI_ADD; ?></h2>					

				
				<?php  $id = $this->id;
    $postUrlUpdate = $this->url(array(
        'controller' => 'ministry',
        //'action'  => 'userview'
        ))."?id=".$this->escape($id); ?>

<form role="form" method="post" action="<?php echo $postUrlUpdate; ?>" name="addMinistry"  id="addMinistry">
        <?php echo $this->errorMessage; ?>
        <?php if($this->mess){?>
        <div class='error-msg'><span class="errors"><?php echo $this->mess; ?></span></div>
        <?php } ?>
		<div class="row">
		  <div class="form-group col-sm-6">
              <label>Language<sup class="require">*</sup>  </label>
              <?php echo $this->form->language; ?>
            </div>
			
			 <?php echo $this->form->lang?>
               
             <div class="form-group col-sm-6">
              <label>Ministry Name<sup class="require">*</sup>  </label>
              <?php echo $this->form->ministry_name; ?>
            </div>
			
			<!-----------Add Captcha Code Script----->
			 <div class="form-group col-sm-4">
				<label>Captcha Code<sup class="require">*</sup></label>
				<p>
					<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left"/>
					<span><a  onclick="
						document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();
						document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>	</span>									
				</p>
				<p class="text-left">										
					<?php echo $this->form->vercode; ?>
				</p>
				<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
            </div>
           <!--------------End Captcha Code------->
           
            <div class="form-group col-md-12 col-sm-12 text-center">
               <button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Submit</button>
                <button type="reset" name="Reset" class="btn active text-center" id="resetButton" onclick="goCancel();"><?php echo CANCEL; ?></button>
            </div>
 </div>
     
</form>
    
    
    




