<noscript>
    <style type="text/css">
        .webform-client-form {display:none;}
    </style>
    <div class="noscriptmsg">
    You don't have javascript enabled.  Good luck with that.
    </div>
</noscript>

<?php 
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;

$role = new Zend_Session_Namespace('role');
$captchanew = new Zend_Session_Namespace('captchanew');
	    $captchanew->captchanew = session_id();
$transferengineer=$this->transferengineer;

//for the searching record
$searchUrl = $this->url(array(
            'controller' => 'managetransaction',
            'action'  => 'pfmsbeneficiary'
            )); 
//for Transaction update to the single beneficiaries
$cmiurl1 = $this->url(array(
        'controller' => 'managetransaction',
        'action' => 'beneficiaryedit'
    ));
//for display the record of single beneficiaries
$viewurl = $this->url(array(
        'controller' => 'managetransaction',
        'action' => 'viewbeneficiariesrecord'
    ));	

$schemename= $this->scheme_id;
$cmidata = $this->cmidata;
//echo "aaaa";exit;
//print_r($cmidata);exit;
$min_id = $cmidata[0]['min_id'] != "" ?  base64_encode($cmidata[0]['min_id']) : isset($_GET['min_id']) ? $_GET['min_id']: "";


$paramid = "scheme_id=".base64_encode($schemename[0]->id)."&min_id=".safexss($_GET['min_id'])."&status=".safexss($_GET['status'])."&scm_type=".safexss($_GET['scm_type']);
$searchUrl = $searchUrl.'?scheme_id='.$schemename[0]->id;
//echo $paramid;exit;
?>

<script type="text/javascript" language="javascript">
$(document).ready(function(){
	$("#sechemSearchCancleButton").click(function(){
		window.location.href="<?php echo '?'.$paramid; ?>";
	});
	
	//$("#schememanualdataform").submit(function (e) {
	$(".validate-captcha").click(function () {
		var bencount = $('#beneficiary_count').val();
		var numericReg = /^\d*[0-9](|.\d*[0-9]|,\d*[0-9])?$/;
		// var capthacode = "<?php echo $_SESSION["vercode"]; ?>";
		// alert(capthacode);
		
		var amtvalue = '';
		for (i = 1; i < bencount; i++) { 
			jQuery("span#fromdate-error" + i).text("");
			var amtval = $('#beneficiary_amount' + i).val();
			amtvalue = amtvalue + amtval;
			if(!numericReg.test(jQuery("#beneficiary_amount" + i).val()) && jQuery("#beneficiary_amount" + i).val() != '') {
				jQuery("#beneficiary_amount" + i).focus();
				jQuery("span#beneficiary_amount-error" + i).text("Only numeric value allowed.");
				return false;
			}else{
				$("span#beneficiary_amount-error" + i).html("");
			}
			if (jQuery("#beneficiary_amount" + i).val() != '') {
				if (jQuery("#fromdate" + i).val() == '') {
					jQuery("#fromdate" + i).focus();
					jQuery("span#fromdate-error" + i).text("Can not be empty.");
					return false;
				}
			}else{
				$("span#fromdate-error" + i).text("");
			}
			if (jQuery("#beneficiary_amount" + i).val() != '') {
				if (jQuery("#todate" + i).val() == '') {
					jQuery("#todate" + i).focus();
					jQuery("span#todate-error" + i).text("Can not be empty.");
					return false;
				}else{
				$("span#todate-error" + i).text("");
				}
			}
			if (jQuery("#beneficiary_amount" + i).val() != '') {
				if (jQuery("#purpose" + i).val() == '') {
					jQuery("#purpose" + i).focus();
					jQuery("span#purpose-error" + i).text("Can not be empty.");
					return false;
				}else{
				$("span#purpose-error" + i).html("");
				}
			}
		}
		if(amtvalue == '') {
			alert('At least one value is required in amount field.');
			jQuery("#beneficiary_amount1").focus();
			return false;
		}
		
		
		
		
	var beneficiary_amount1,beneficiary_remark1,vercode,tempvar;
	tempvar = "";
    beneficiary_amount1 = $('#beneficiary_amount1').val();
    beneficiary_remark1 = $('#beneficiary_remark1').val();
	vercode = $('#vercode').val();
	if(vercode == '' || vercode == null){
		$("span#captcha-error").text("Captcha can\'t be empty." );
		$("#vercode").focus();
		return false;
	}
	else if(vercode != '' || vercode != null){
			$.ajax({
			type:"POST",
			data:{vercode:vercode},
			url:"<?php echo $this->baseUrl('managetransaction/checkvercode');?>",
			dataType:"JSON",
			async: false,
			success:function(response){
			//alert(response+"ccc");
			if(response == "failed"){
				tempvar="stop";
				$("span#captcha-error").text("Please enter a valid Captcha code.");
				$("#vercode").focus();
				return false;
			 }else if(response == "successful"){
				tempvar="successful";
				$("span#captcha-error").text("");
				//return false;
				}
			}
		});
		}
		if(tempvar == "stop"){
			return false;		
		}
	}); //schememanualdataform
});

</script>
<!--- ************************************************* --->

<ol class="breadcrumb">
   <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
   <li><a href="<?php echo $this->baseUrl('managetransaction/schemeview'); ?>">Scheme List</a></li>
   <li class="active"><?php echo T_FIRST_TAB_MSG;?></li>
</ol>


<!--- ************************************************* --->
<?php if($this->errorMessage){?>
	<div class='require'><span><?php echo $this->errorMessage; ?></span></div>
	<?php } ?>
<div class="row">
<div class="col-sm-9 col-xs-12"><h2><?php $schemename= $this->scheme_id; 
if(isset($_GET['scm_type']) && base64_decode($_GET['scm_type']) == 1){
			$type = " (In Cash)";
		}else if(isset($_GET['scm_type']) && base64_decode($_GET['scm_type']) == 2){
			$type = " (In Kind)";
		}else if(isset($_GET['scm_type']) && base64_decode($_GET['scm_type']) == 3){
			$type = " (In Others)";
		}else{
			$type = "";
		}
echo "Scheme Name : ".$schemename[0]->scheme_name.$type."&nbsp;&nbsp; Scheme Code: ".$this->scheme_code[0]['scheme_codification'];
?>  </h2> </div>
<div class="col-sm-3 col-xs-12 text-right"><a href="<?php echo $this->baseUrl('/samplecsv/DBT-Schemes-Management-User-Manual-Manage-Beneficiary-v1.pdf'); ?>"  target="_blank">Help?</a></div></div>

   <div class="row">
	  <div class="col-sm-12">
	
 
<?php
//echo "<pre>";print_r($this->cmidata);echo "</pre>";die;
        $cmidata = $this->cmidata;
        $Count = $this->counttotalcmireports;
	   $min_id = $min_id;
	   //echo $min_id;exit;
        $cmidata = $this->cmidata;
        $Count = $this->counttotalcmireports;
		if($this->successMsg){
            echo "<div class='success-msg'>".$this->successMsg."</div>"; 
        }
       if(isset($_GET['success']) && $_GET['success']){
            echo "<div class='success-msg'>Transaction has been uploaded successfully.</div>"; 
        } 

?>
<div class="webform-client-form">

<form role="form" class="form-inline" method="get" action="<?=$searchUrl.'?search='.$searchUrl?>">
        <div class="row margin-bottom-10">
		
			<div class="col-sm-12">
				<div class="form-group margin-left-15">
					<label><?php //echo SEARCH_BY; ?></label>
				<!--<span class="dateinput">
					<input class="rolBtn form-control" type="date" name="dob" id="to" value="<?php //if(isset($_GET['dob'])){ echo $_GET['dob']; }?>" placeholder="mm/dd/yy"/>
				</span>-->
					<input class="rolBtn form-control" type="text" name="benef_id" value="<?php if(isset($_GET['benef_id'])){ echo safexss($_GET['benef_id']);} ?>" placeholder="Unique ID"/>
					
					<input class="rolBtn form-control" type="text" name="name" value="<?php if(isset($_GET['name'])){ echo safexss($_GET['name']);} ?>" placeholder="Name"/>
					
					<input class="rolBtn form-control" type="hidden" name="scheme_id" value="<?php echo base64_encode($schemename[0]->id); ?>"/>
					<input class="rolBtn form-control" type="hidden" name="min_id" value="<?php echo base64_encode($schemename[0]->ministry_id); ?>"/>
					<input class="rolBtn form-control" type="hidden" name="status" value="<?php  echo safexss($_GET['status']);?>"/>
					<input class="rolBtn form-control" type="hidden" name="scm_type" value="<?php  echo safexss($_GET['scm_type']);?>"/>
					<button type="Submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Search</button>
					<button type="reset" class="btn active text-center" name="reset" id="sechemSearchCancleButton">Reset</button>
				</div>
			</div>
            </div>
		</form>
		
		<div class="row"><div class="col-sm-12">
			<?php 
			//below initialization using exporting filter wise data
			$to = $from = $benef_id = $st = $dt = $bl = $vi = null;
			if(isset($_GET['benef_id'])){
				$benef_id = $_GET['benef_id'];
			}
			if(isset($_GET['name'])){
				$name = $_GET['name'];
			}
			if(isset($_GET['dob'])){
				$dob = $_GET['dob'];
			}
			$paramtobeexp = "&benef_id=".$benef_id."&name=".$name."&dob=".$dob;

			?>
			
			<div class="row">
			
		<div class="col-sm-12 text-right">
						<!--<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/managetransaction/csvexportfortransaction?scheme_id=<?php echo base64_encode($schemename[0]->id); ?>&min_id=<?php echo $min_id; ?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?><?php echo $paramtobeexp; ?>&exppageno=<?php echo base64_encode(1);?>" title="<?php echo 'Export Data of Current Scheme'; ?>"><?php echo 'Export for Transaction'; ?></a>
				
					<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/schemeowner/beneficiaryrecord?scheme_id=<?php echo base64_encode($schemename[0]->id); ?>&min_id=<?php echo $min_id; ?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?>" title="<?php echo 'Add scheme data'; ?>"><?php echo 'Add Beneficiary'; ?></a>
				
				
				
					<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/schemeowner/importscheme?scheme_id=<?php echo base64_encode($schemename[0]->id);?>&scheme_name=<?php echo base64_encode($schemename[0]->scheme_name);?>&min_id=<?php echo $min_id;?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?>" title="<?php echo 'Import Beneficiaries file.'; ?>"><?php echo 'Import Beneficiaries'; ?></a>-->

				<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/managetransaction/importbulktransaction?scheme_id=<?php echo base64_encode($schemename[0]->id);?>&scheme_name=<?php echo base64_encode($schemename[0]->scheme_name);?>&min_id=<?php echo $min_id;?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?>" title="<?php echo 'Import Transaction file for payment initiation'; ?>"><?php echo 'Import Transaction file for payment initiation'; ?></a>
					
				
			</div>
            </div>

<div class="row">
<div class="col-sm-12">
 <ul class="nav nav-tabs">
  
<li>

				<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/managetransaction/pfmsbeneficiary?scheme_id=<?php echo base64_encode($schemename[0]->id);?>&scheme_name=<?php echo base64_encode($schemename[0]->scheme_name);?>&min_id=<?php echo $min_id;?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?>" title="<?php echo T_FIRST_TAB_MSG;?>"><?php echo T_FIRST_TAB_MSG;?></a>
</li>
<li class="active">

				<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/managetransaction/showpfmstransactionxml?scheme_id=<?php echo base64_encode($schemename[0]->id);?>&scheme_name=<?php echo base64_encode($schemename[0]->scheme_name);?>&min_id=<?php echo $min_id;?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?>" title="<?php echo T_SECOND_TAB_MSG;?>"><?php echo T_SECOND_TAB_MSG;?></a>
</li>
<li class="active">

				<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/managetransaction/pfmspendingtransactionhistory?scheme_id=<?php echo base64_encode($schemename[0]->id);?>&scheme_name=<?php echo base64_encode($schemename[0]->scheme_name);?>&min_id=<?php echo $min_id;?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?>" title="<?php echo T_THIRED_TAB_MSG;?>"><?php echo T_THIRED_TAB_MSG;?></a>
</li>
<li class="active">

				<a class="btn btn-warning" href="<?php echo $this->baseUrl(); ?>/managetransaction/pfmstransactionhistory?scheme_id=<?php echo base64_encode($schemename[0]->id);?>&scheme_name=<?php echo base64_encode($schemename[0]->scheme_name);?>&min_id=<?php echo $min_id;?>&scm_type=<?php echo safexss($_GET['scm_type']);?>&status=<?php echo safexss($_GET['status'])?>" title="<?php echo T_FOURTH_TAB_MSG;?>"><?php echo T_FOURTH_TAB_MSG;?></a>
</li>

</ul>
			</div>
			</div>
          
		<div class="row">
			<div class="col-sm-12 record_box">
				<div class="tabaddar">
					<div class="text-center">
				<?php if($Count): echo $Count ." ".RECORD_FOUND; endif;?>
				<?php if(!$Count): echo 0 ." ".RECORD_FOUND; endif;?>
			
		</div>

		
		<?php $postUrl = $this->url(array(
                'controller' => 'aadharvalidateapi',
                'action'  => 'createpfmsxml'
            )); 
        ?> 
		
		
		
        <div class="table table-responsive">
		<table class="table" summary="schemes name" id='tablecheck'>
            <thead>
                <tr>
                    
                    <th scope="col"><?php echo SNo; ?></th>
					<!--<th scope="col">Scheme Type</th>-->
					<th scope="col">Name</th>
                    <th scope="col">Unique ID</th>
                    <!--<th scope="col">Email ID</th>-->
					<th scope="col">Aadhaar Number</th>
					<th scope="col">Aadhaar Validated Status</th>
					<th scope="col">Payment Mode</th>
					<th scope="col">Amount(Rs)</th>
					<th scope="col">From&nbsp;Payment&nbsp;date</th>
					<th scope="col">To&nbsp;Payment&nbsp;Date</th>
					<th scope="col">Purpose</th>
					<th scope="col">Remark</th>
                </tr>
<?php if(isset($_GET['actmsg']) && $_GET['actmsg']=='notaddamt'){
            echo "<tr><td colspan='12' class='text-center'><div class='error-msg'>Atleast fill one record.</div></td></tr>"; 
        }?>
            </thead>
<form class="webform-client-form form-inline" method="post" accept-charset="UTF-8"  name="schememanualdataform" id="schememanualdataform">
			 <tbody>
	<?php if($Count==0){ ?>
			<tr>
				<td colspan="12" class="text-center"><?php echo RECORD_EMPTY;?></td>
			</tr><?php
		}else{
            $i=1;
			$month_val = array('01' => 'January', '02' => 'February', '03' => 'March', '04' => 'April', '05' => 'May', '06' => 'June', '07' => 'July', '08' => 'August', '09' => 'September', '10' => 'October', '11' => 'November', '12' => 'December');
		//echo "<pre>";print_r($cmidata);die;
            foreach ($cmidata as $key => $val){
				// print '<pre>';
				// print_r($val);
				// die;
		?>
        <tr>
		
		<td><?php echo $i+$this->start;?></td>
		
		
		
		<td><?php echo $this->escape($val['name']);?></td>
		<td><?php echo $this->escape($val['uniq_user_id']);?></td>
		<!--<td><?php //echo $this->escape($val['email_id']);?></td>-->
		<td><?php
			echo $this->escape($val['aadhar_num']);?>
		</td>
		<td><?php
			 if($this->escape($val['uidai_aadhar_validate']==0)){ echo "N";}elseif($this->escape($val['uidai_aadhar_validate']==1)){ echo "Y";}elseif($this->escape($val['uidai_aadhar_validate']==2)){ echo "Failed to Aadhaar validate";}?>
		</td>
			
		<td>
<?php if($this->escape($val['aadhar_validate']==1)){ echo "APB";}else{ echo "NEFT";}?>
		</td>
	     <td> 
		<?php if(isset($_GET['scm_type']) && base64_decode($_GET['scm_type'])==2){?>
		 <select name="beneficiary_amount<?php echo $i; ?>[]" id="beneficiary_amount<?php echo $i; ?>" class="form-control">
		<option value="">==Select Option==</option>
		<option value="Bio Authentication">Bio Authentication</option>
		<option value="Demographic Authentication">Demographic Authentication</option>
		<option value="Manual Validation">Manual Validation</option>
		</select><span class="require" id="beneficiary_amount-error"></span>
		<?php }else{?> <input type="text" name="beneficiary_amount<?php echo $i; ?>[]" id="beneficiary_amount<?php echo $i; ?>" value="" class="form-control" maxlength="20" placeholder="Amount">
		<span class="require" id="beneficiary_amount-error<?php echo $i; ?>"></span>
		<?php }?>
		</td>
		<td class="fromdate">
		<input type="text" name="beneficiary_amount<?php echo $i; ?>[]" rel="<?php echo $i; ?>" id="fromdate<?php echo $i; ?>" class="form-control" maxlength="40" placeholder="dd-mm-yyyy" readonly="readonly">

			<span class="require" id="fromdate-error<?php echo $i; ?>"></span>
		</td>
		<td class="fromdate">
		<input type="text" name="beneficiary_amount<?php echo $i; ?>[]" id="todate<?php echo $i; ?>" value="" class="form-control" maxlength="20" placeholder="dd-mm-yyyy" readonly="readonly">

			<span class="require" id="todate-error<?php echo $i; ?>"></span>
		</td>
		<td>
		<input type="text" name="beneficiary_amount<?php echo $i; ?>[]" id="purpose<?php echo $i; ?>" value="" class="form-control" width="40" maxlength="20" placeholder="Installment no.">

			<span class="require" id="purpose-error<?php echo $i; ?>"></span>
		</td>
		<td>
		<textarea type="text" name="beneficiary_amount<?php echo $i; ?>[]" id="beneficiary_remark<?php echo $i; ?>" class="form-control" maxlength="250" placeholder="Remark"></textarea>

			<span class="require" id="beneficiary_remark-error"></span>
		</td>
		</tr>
        
        <input type="hidden" id ="beneficiary_amount<?php echo $i;?>"  name ="beneficiary_amount<?php echo $i;?>[]" value="<?php echo $this->escape($val['id']);?>" />
		<input type="hidden" id ="beneficiary_amount<?php echo $i;?>"  name ="beneficiary_amount<?php echo $i;?>[]" value="<?php echo $this->escape($val['uniq_user_id']);?>" />
		<input type="hidden" id ="beneficiary_amount<?php echo $i;?>"  name ="beneficiary_amount<?php echo $i;?>[]" value="<?php if($this->escape($val['aadhar_validate']==1)){ echo "APB";}else{ echo "NEFT";}?>" />
		<?php ++$i;
			
		} 
		?>
		
		<input type="hidden" id ="beneficiary_count"  name ="beneficiary_count" value="<?php echo $i;?>" />
		
		<?php } ?>
        
        <?php if($Count>0){ ?>
        <tr>
        <td colspan="9">Note: After adding transaction information, these transactions will be available in payment file for payment processing.</td>
        <td  colspan="3">
        	

<!-----------Add Captcha Code Script----->
			
			<div class="form-group captcha-inner pull-right">
				<label>Captcha Code<sup class="require">*</sup>  </label>
                <?php echo $this->form->vercode; ?>
				<p>
					<span><img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left"/></span>	
					<a  onclick="
						document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();
						document.getElementById('vercode').focus();"
						id="change-image" class="menu4 refresh" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>
													
				</p>
				<div class="c-left text-left"><span class="require" id="captcha-error"></span></div>
				
				<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
 
				</div>
               
         
           <!--------------End Captcha Code------->
               

        </td>
        
        </tr>
        
        <tr>
        	<td colspan="12" class="text-center">
            <button type="submit" name="Submit" class="btn btn-default btn-warning validate-captcha" id="sechemSearchButton sechemSearchButtonnew">Submit</button>

            </td>
        </tr>
        <?php }?>
        
        
	
		</tbody> 
        </form>
			</table></div>  



          
		
</div></div></div>



</div>
<div class="text-center">
<?php
    echo $this->paginate;
    ?>
</div>
		</div>
	</div>


<script type="text/javascript">
	$(document).ready(function() {
	<?php $count=sizeof($cmidata)+1;for($i=1;$i<$count;$i++){?>
    
		var yearval  = null;
		yearval = new Date().getFullYear();
    $("#fromdate<?php echo $i;?>").datepicker({
            dateFormat: 'dd-mm-yy',
            changeMonth: true,
            changeYear: true,
            showOn: 'button',
			yearRange: '1920:'+yearval,
			defaultYear: yearval,
			//maxDate: new Date(),
            buttonImage: '<?php echo $this->baseUrl("images/calendar-blue.png"); ?>'
        });
    });
	 $(document).ready(function() {
		var yearval  = null;
		yearval = new Date().getFullYear();
    $("#todate<?php echo $i;?>").datepicker({
            dateFormat: 'dd-mm-yy',
            changeMonth: true,
            changeYear: true,
            showOn: 'button',
			yearRange: '1920:'+yearval,
			defaultYear: yearval,
			//maxDate: new Date(),
            buttonImage: '<?php echo $this->baseUrl("images/calendar-blue.png"); ?>'
        });
    
<?php }?>


$(".hasDatepicker").change(function(){
	var selectId = minDate = increase_num = '';
	selectId = $(this).attr("id");
	increase_num = $(this).attr("rel");
	minDate = $("#"+selectId).val();
	$('#todate'+increase_num).datepicker('setDate', minDate);
	//$('#todate'+increase_num).datepicker('option', 'maxDate', 0);
	$('#todate'+increase_num).datepicker('option', 'minDate', minDate);
	//alert(minDate);
});


});
</script>			
