<?php 
$userid = new Zend_Session_Namespace('userid');
$unme= $userid->userid;
$role = new Zend_Session_Namespace('role');
?>
<script type="text/javascript" language="javascript">
jQuery(document).ready(function(){
	jQuery(".rstbtn").click(function(){
		jQuery(".srch-box").val('');
		window.location.href="<?php echo $searchUrl; ?>";
	});
});
</script>

<ol class="breadcrumb">
   <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
   <li class="active">Scheme List</li>
</ol>

<h2><!--Scheme List--><?php //if($role->role == 4){ ?>
           <!--<a class="pull-right" href="<?php //echo $this->baseUrl('/samplecsv/schemeownerdata_usermanual.pdf'); ?>" target="_blank">Help?</a> -->      
<?php // } ?></h2>

 <div class="row">
<div class="col-sm-12 text-right"><a href="<?php echo $this->baseUrl('/samplecsv/DBT_App_User_Manual_Manage_Transactions_V3.pdf'); ?>"  target="_blank">Help?</a></div></div>

	
    <?php
        $cmidata = $this->dataFound;
        $Count = $this->dataFound;
        if($this->successMsg){
            echo "<div class='success-msg'>".$this->successMsg."</div>"; 
        }
				if($_GET['notfound']){
					echo '<hr /><p class="error-msg">'."Unable to upload record!".'</p>';
				}else if($_GET['alreadyexist']){
                    echo '<hr /><p class="error-msg">'."Record is already exist in Manual data!".'</p>';
                }
                else if($_GET['success']){
					echo '<hr /><p class="success-msg">'."Your record has been successfully inserted".'</p>';					
				}
			   if(is_array($this->dataFound)) {
			?>
				<div class='row'><div class="col-sm-12 text-center record_box"><?php echo Count($this->dataFound)." ".RECORD_FOUND;?></div></div>
			<?php } ?>


    <form  class="form-inline webform-client-form" method="post" accept-charset="UTF-8" action="<?php echo $postUrl; ?>">
       <div class="table table-responsive">
        <table class="table" summary="scheme list">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Scheme Name</th>
                    <th scope="col">Scheme Type</th>
                    <th scope="col">Ministry</th>							
                    <th scope="col">Action</th>
                   
                </tr>
            </thead>
            <tbody><?php if(!is_array($this->dataFound) || count($this->dataFound) == 0){
                    ?>
                        <tr>
                            <td colspan="10" class='text-center'><?php echo RECORD_EMPTY;?></td>
                        </tr>
                    <?php
                    }else{
                        $i=1;
                        foreach ($cmidata as $key => $val)
                        { 
							// print '<pre>'; print_r($val);
						?>
                            <tr>
                                <td><?php echo $i; ?></td>
                                <td> <?php echo $this->escape($val['scheme']);?></td>
                                <td><?php 
                                        if($val['scheme_type'] == 0){
                                            echo "All";
                                        }else if($val['scheme_type'] == 1){
                                            echo "In Cash";
                                        }else if($val['scheme_type'] == 2){
                                            echo "In Kind";
                                        }else if($val['scheme_type'] == 3){
                                            echo "In Others";
                                        }
                                    ?>
                                </td>
                                <td> <?php echo $this->escape($val['ministry']);?></td>
                                <td> 
								<!--
								<a href="<?php //echo $this->baseUrl(); ?>/schememanualdata/schemedatalist?scheme_id=<?php //echo base64_encode($this->escape($val['sid']));?>&min_id=<?php //echo base64_encode($this->escape($val['mid']));?>" class="menu1">Manual Data</a>
								-->
								
								
								
								<?php if($val['scheme_type'] != 2 && $val['pfms_scheme_code'] != ''){ ?>
									<a href="<?php echo $this->baseUrl(); ?>/managetransaction/beneficiarydatalist?scheme_id=<?php echo base64_encode($this->escape($val['sid']));?>&min_id=<?php echo base64_encode($this->escape($val['mid']));?>&scm_type=<?php echo base64_encode($val['scheme_type']);?>" class="menu1">Manage Transaction</a>
									/<a href="<?php echo $this->baseUrl(); ?>/managetransaction/pfmsbeneficiary?scheme_id=<?php echo base64_encode($this->escape($val['sid']));?>&min_id=<?php echo base64_encode($this->escape($val['mid']));?>&scm_type=<?php echo base64_encode($val['scheme_type']);?>" class="menu1">Manage PFMS Transaction</a>
								<?php } else if($val['scheme_type'] != 2 && $val['pfms_scheme_code'] == '') { ?>
									<a href="<?php echo $this->baseUrl(); ?>/managetransaction/beneficiarieslist?scheme_id=<?php echo base64_encode($this->escape($val['sid']));?>&min_id=<?php echo base64_encode($this->escape($val['mid']));?>&scm_type=<?php echo base64_encode($val['scheme_type']);?>" class="menu1">Manage Transaction</a>
									/<a href="<?php echo $this->baseUrl(); ?>/managetransaction/paymentinitialization?scheme_id=<?php echo base64_encode($this->escape($val['sid']));?>&min_id=<?php echo base64_encode($this->escape($val['mid']));?>&scm_type=<?php echo base64_encode($val['scheme_type']);?>" class="menu1">Manage Transaction for Bank</a>
								<?php } else { ?>
									<a href="<?php echo $this->baseUrl(); ?>/managetransaction/beneficiarieslist?scheme_id=<?php echo base64_encode($this->escape($val['sid']));?>&min_id=<?php echo base64_encode($this->escape($val['mid']));?>&scm_type=<?php echo base64_encode($val['scheme_type']);?>" class="menu1">Manage Transaction</a>
								<?php } ?>
                                </td>
                                 

                            </tr>
                            <?php ++$i;
                        }
                    } ?>
                </tbody> 
        </table>
</div>
    </form>
    <?php //echo $this->paginate; ?>

		
