
<header class="container-fluid">
<div class="row">
        <div class="col-md-6 col-sm-10 col-xs-10">
                <a href="/" class="navbar-brand"><img src="<?php echo $this->baseUrl('images/logo.png');?>" alt="DBT" /><span class="rightlogo"><span><?php echo scheme_management_system; ?></span><small><?php echo govt_of_india; ?></small></span></a>
               
        </div>
        
        <div class="col-md-6 col-sm-2 col-xs-2">
                <a href="javascript:void(0);" class="emblembox pull-right"><img src="<?php echo $this->baseUrl('images/indian_emblem.png');?>" class="rightemblem" alt="Indian Emblem" /><!-- <span class="rightlogo"><span><?php //echo direct_benefit_transfer; ?></span><small><?php //echo govt_of_india; ?></small></span>--></a>
             
        </div>
        </div>
</header>
