<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title><?php echo WEBSITE_TITLE;?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		
		
		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/style.css'); ?>">
		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/print.css'); ?>" media="print">
		<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
		<script type="text/javascript" src="<?=$this->baseUrl('js/jquery.min.js') ?>"></script>
		<script type="text/javascript" src="<?=$this->baseUrl('js/jquery.passwordstrength.js') ?>"></script>
		<script type="text/javascript" src="<?=$this->baseUrl('js/application.js') ?>"></script>

		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/style1.css'); ?>" media="screen" />
		<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/font-awesome.css'); ?>" media="screen" />



	</head>
	<body>
	fghfhfghgf
</body>
</html>
<h2>dilip</h2>
<?php //echo "dilip kumar"; die;?>