<?php 
	$url_arg = $this->userAgent()->getServerValue('request_uri'); 
	$args = explode("/", $url_arg);
	$role = new Zend_Session_Namespace('role');


?>
<div class="tlc navigation">
	<ul class="tabs">
<?php if($role->role == 1){ ?>
		<?php if($args[2] == 'user' && ($args[3] == 'userinfo' || $args[3] == 'userinfoedit' || $args[3] == 'changeuserpassword')){ ?>
			<li><a href="/dbt/user/userinfo" title="<?php echo MY_ACCOUNT; ?>" class="active" ><?php echo MY_ACCOUNT; ?></a></li>
		<?php } ?>
		<li><a href="/dbt/user/userview" title="Users" class=<?php if($args[2] == 'user') { echo 'active';} ?>>Users</a></li>

		<li><a href="/dbt/role/roleview" title="Roles" class=<?php if($args[2] == 'role') { echo 'active';} ?>>Roles</a></li>

		<li><a href="/dbt/ministry/ministryview" title="Ministry" class=<?php if($args[2] == 'ministry') { echo 'active';} ?>>Ministry</a></li>

		<li><a href="/dbt/scheme/schemeview" title="Scheme" class=<?php if($args[2] == 'location') { echo 'active';} ?>>Scheme</a></li>

		<li><a href="/dbt/category/categoryview" title="Category" class=<?php if($args[2] == 'category') { echo 'active';} ?>>Category</a></li>

		<li><a href="/dbt/schememanualdata/schememanualdataview" title="Scheme Manual Data" class=<?php if($args[2] == 'schememanualdata') { echo 'active';} ?>>Scheme Manual Data</a></li>

		<li><a href="/dbt/contentmanagement/contentmanagementview" title="Content Management" class=<?php if($args[2] == 'contentmanagement') { echo 'active';} ?>>Content Management</a></li>

		<li><a href="/dbt/feedback/feedbackview" title="Feedback" class=<?php if($args[2] == 'feedback') { echo 'active';} ?>>Feedback</a></li>

		<li><a href="/dbt/block/import" title="Block" class=<?php if($args[2] == 'block') { echo 'active';} ?>>Block</a></li>



<?php } else if($role->role == 4) { ?>
<!--<li><a href="/dbt/schemeowner/schemeview" title="Scheme List" class=<?php /*if($args[2] == 'schemeowner') { echo 'active';}*/ ?>>Scheme List</a></li>-->

<?php } ?>
    </ul>
</div>