<?PHP


class Application_Form_Scheme extends Zend_Form
{

public function init()
{
// Set the method for the display form to POST
}

public function addform(){
	$role = new Zend_Session_Namespace('role');
		// Set the method for the display form to POST
        $this->setMethod('post');
		$this->addElement('text', 'scheme_name', array( 			
            'required'   => true,
            'class'   => 'form-control',
			'placeholder' => 'Scheme Name',
            'filters'    => array('StringTrim'),
			'maxlength'  => '150',
			'decorators'=>Array(
			'ViewHelper','Errors'
		   ),
            'validators' => array(
			    array('notEmpty', true, array(
                    'messages' => array(
                        'isEmpty'   =>  'Scheme name can\'t be empty'
                    )
                ))),          
			));
  
  
  
/************ Add language Element 28th june ******************/
 $language = new Zend_Form_Element_Select('language',array(  
            'label'        => '',
            'required'   => true,
            'class'   => 'form-control',
			//'registerInArrayValidator' => false,
            'multiOptions' => array(
            '0'    => '--Select Language--',
                      
        ),
		    'decorators'=>Array(
			'ViewHelper','Errors'
		   ),
		   'attribs'    => array('disabled' => 'disabled')	
		
		 ));
     $required = new Zend_Validate_NotEmpty();
     $required->setType ($required->getType() | Zend_Validate_NotEmpty::INTEGER | Zend_Validate_NotEmpty::ZERO);
			$language->addValidators (array($required));
        $objlang = new Application_Model_Contentmanagement; 
	 	$showlanguage = $objlang->language(); 
        $language->setValue("2");
		foreach($showlanguage as $key => $value){
			$name = $value['title'];			
			$language->addMultiOption($value['id'], $name);
		}
        $this->addElement($language);

/****************** end **********************/  
/************* Add Language Hidden field *****/
    $this->addElement('hidden', 'lang', array( 			
            'required'   => true,
            'type' => 'hidden',
             'class'   => 'form-control',
            'filters'    => array('StringTrim'),
			'maxlength'  => '100',
			'value' => '2',
			'decorators'=>Array(
			'ViewHelper','Errors'
		   )        
  ));
/******************** end***************/		
		//// project field select box
		
	  $ministry = new Zend_Form_Element_Select('ministry_id',array(  
            'label'        => '',
            'required'   => true,
            //'registerInArrayValidator' => false,
            'class'   => 'form-control',
            'multiOptions' => array(
            '0'    => '--Select Ministry--',
                      
        ),
		    'decorators'=>Array(
			'ViewHelper','Errors'
		   ),
		
		 ));
     $required = new Zend_Validate_NotEmpty ();
     $required->setType ($required->getType() | Zend_Validate_NotEmpty::INTEGER | Zend_Validate_NotEmpty::ZERO);
			$ministry->addValidators (array($required));
          
        $objministry = new Application_Model_DbtMinistry;
		if($role->role == 6){
			$minid= '';
			$min = new Zend_Session_Namespace('ministryid');
			$minid = $min->ministryid;
			$showministryname = $objministry->ministryUser($minid);
		}else{
			$showministryname = $objministry->roleuser();
		}
	 	// echo "<pre>";
	 	// print_r($showministryname);
	 	// echo "</pre>";
	 	// exit;
		foreach($showministryname as $key => $value){
			$name = $value['ministry_name'];			
			$ministry->addMultiOption($value['id'], $name);
		}
        $this->addElement($ministry);
		
		
		$this->addElement('text', 'scheme_codification', array( 			
            'required'   => true,
            'class'   => 'form-control scheme_codification',
            'filters'    => array('StringTrim'),
			'placeholder' => 'Generated by DBT Bharat',
			'maxlength'  => '7',
			'decorators'=>Array(
			'ViewHelper','Errors'
		   ),
            'validators' => array(
			    array('notEmpty', true, array(
                    'messages' => array(
                        'isEmpty'   =>  'Scheme code can\'t be empty'
                    )
                ))
			),          
		));
		
		//Add PFMS Scheme Code
		$this->addElement('text', 'pfms_scheme_code', array( 			
            'required'   => false,
            'class'   => 'form-control scheme_codification',
            'filters'    => array('StringTrim'),
			'placeholder' => 'Provided By PFMS',
			'maxlength'  => '7',
			'decorators'=>Array(
			'ViewHelper','Errors'
		   ),         
		));
 
//to add schme type
        $schmeType = new Zend_Form_Element_Select('scheme_type',array(  
            'label'        => '',
            'required'   => true,
            //'registerInArrayValidator' => false,
            'class'   => 'form-control',
            'multiOptions' => array(
            '0'    => '==Select Benefit Type==',
            '1'    => 'In Cash',
            '2'    => 'In Kind',
            '3'    => 'In Others',
                      
        ),
		    'decorators'=>Array(
			'ViewHelper','Errors'
		   ),w
		 ));
     $requiredtype = new Zend_Validate_NotEmpty ();
     $requiredtype->setType ($requiredtype->getType() | Zend_Validate_NotEmpty::INTEGER | Zend_Validate_NotEmpty::ZERO);
	$schmeType->addValidators (array($requiredtype));
        $this->addElement($schmeType);
//add schme type end here

//About scheme description
        $this->addElement('textarea', 'description', array( 			
            'required'   => false,
			 //'class'   => 'mceEditor',
			 //'id' => 'mceEditor',
                           'class'   => 'form-control',
			 'id' => 'editor1',
            'filters'    => array('StringTrim'),
			'maxlength'  => '10000',
			'cols' => '1000',
			'decorators'=>Array(
			'ViewHelper','Errors'
		   ),
            'validators' => array(
			    array('notEmpty', true, array(
                    'messages' => array(
                        'isEmpty'   =>  'Descrption can\'t be empty'
                    )
                )),),          
  ));
//scheme description

            $this->addElement('file', 'uploadscheme', array( 
                            'label'      => '',
                            'required'   => false,
                            'id' => 'uploadscheme',
                            ));
  
	// Add a captcha
        $this->addElement('text', 'vercode', array(
            //'label'      => 'Please enter the 5 letters displayed below:',
            'required'   => true,
			'class'   => 'form-control captchain',
			'placeholder' => 'Captcha',
				 'autocomplete' => 'off',
				'decorators'=>Array(
			'ViewHelper',
			'Errors',
		   ),
            'validators' => array(
                array('validator' => 'StringLength', 'options' => array(0, 20))
                )
        ));
		/*******change in the form  folder in scheme.php *****************/

//to add schme group 25th oct 
        $schmeGroup = new Zend_Form_Element_Select('scheme_group',array(  
            'label'        => '',
            'required'   => true,
            //'registerInArrayValidator' => false,
            'class'   => 'form-control',
            'multiOptions' => array(
            '0'    => '==Select Type Of The Scheme==',
            '1'    => 'Central Sector Scheme',
            //'2'    => 'State/UTs Scheme',    
            '3'    => 'Centrally Sponsored Scheme', 
           // '4'    => 'District Scheme',   			
        ),
		    'decorators'=>Array(
			'ViewHelper','Errors'
		   ),
		 ));
    $requiredtype = new Zend_Validate_NotEmpty ();
    $requiredtype->setType ($requiredtype->getType() | Zend_Validate_NotEmpty::INTEGER | Zend_Validate_NotEmpty::ZERO);
	$schmeGroup->addValidators (array($requiredtype));
    $this->addElement($schmeGroup);
//add schme group end here

        // Add the submit button
        $this->addElement('submit', 'submit', array(
            'ignore'   => true,
            'label'    => 'Submit',
        ));

        // And finally add some CSRF protection
        $this->addElement('hash', 'csrf', array(
            'ignore' => true,
        ));

		
	}

}
