<?php
$userid = new Zend_Session_Namespace('userid');
        $admname = new Zend_Session_Namespace('adminMname');
	 $role = new Zend_Session_Namespace('role');
	// echo "ROLE=".$role->role;
	$captchanew = new Zend_Session_Namespace('captchanew');
	$captchanew->captchanew = session_id();
	?>

<script type="text/javascript" language="javascript">
/***************************************************/
// Mixing the password for login credintial
function mixUpValues(ecyn,keyt,keyt1)
{
	var stringis;
	stringis=ecyn.substr(0,12);
	stringis+=keyt;
	stringis+=ecyn.substr(12,10);
	stringis+=keyt1;
	stringis+=ecyn.substr(22);
	return stringis;
}

/*************************************************/
function valPwd2()
	{
		var iChars = "',\\\;&<>\"";
		var iChars1 = "',\\\;&<>\"~@#$%^*()_?><+_-|`:";
		var iChars_sec = "',\\\;&<>\"~@#$%^*()_><+_-|`:";
			/*********************************************************************************/
			if(document.frm_change.oldpassword.value=='' || document.frm_change.oldpassword.value == null){
						document.getElementById('old-pass').innerHTML="Old Password should not be blank.";
						document.frm_change.oldpassword.focus();
						return false;
						
			}
			if(document.frm_change.oldpassword.value!="")
				{
					//var encp=MD5(document.frm_change.oldpassword.value);
					//document.frm_change.oldpassword.value=mixUpValues(encp,document.frm_change.keyy.value,document.frm_change.keyy1.value);
					document.getElementById('old-pass').innerHTML="";
					var hash = CryptoJS.HmacSHA256(document.frm_change.oldpassword.value, "");
					document.frm_change.oldpassword.value=mixUpValues(hash.toString(),document.frm_change.keyy.value,document.frm_change.keyy1.value);
			
			
				}


			if(document.frm_change.newpassword.value=='' || document.frm_change.newpassword.value== null)
			{
						document.getElementById('new-pass').innerHTML="New Password should not be blank.";
						document.frm_change.newpassword.focus();
						return false;
						
			}

			
		/*************************************************************************************/

			if(document.frm_change.newpassword.value!=''|| document.frm_change.newpassword.value!=null){
			var passwordval=document.frm_change.newpassword.value;
			if(/^(?=.*\d)(?=.*[@#\-_$%^&+=§!\?])(?=.*[a-z])(?=.*[A-Z])[0-9A-Za-z@#\-_$%^&+=§!\?]{8,20}$/.test(passwordval) == false){
			$('#new-pass').text("Your password quality is too bad. Please use some special character,Numbers,Upper case Letter and Lower case letter!");
			   document.frm_change.newpassword.focus();
			   return false;
			}else{
				$('#new-pass').text("");
			}
			}else{
				$('#new-pass').text("");
		}

		if(document.frm_change.newpassword.value!='')
			{
				document.getElementById('new-pass').innerHTML=""
				if(document.frm_change.newpassword.value.length < 8)
					{
						document.getElementById('new-pass').innerHTML="New Password should contain 8 characters.";
						document.frm_change.newpassword.focus();
						return false;
					}
					
					for (var i = 0; i < document.frm_change.newpassword.value.length; i++) {
						if (iChars.indexOf(document.frm_change.newpassword.value.charAt(i)) != -1) {
							document.getElementById('new-pass').innerHTML="New Password field is either empty or contains space or disallowed character ( \' \\\ < > & , ; \"  ). Please correct and try again.";
							document.frm_change.newpassword.focus();
							return false;
						}
				  }
			}
			if(document.frm_change.newpassword.value!="")
			{
				//var encp=MD5(document.frm_change.newpassword.value);
				//document.frm_change.newpassword.value=mixUpValues(encp,document.frm_change.keyy2.value,document.frm_change.keyy3.value);
				var hash = CryptoJS.HmacSHA256(document.frm_change.newpassword.value, "");
				document.frm_change.newpassword.value=mixUpValues(hash.toString(),document.frm_change.keyy2.value,document.frm_change.keyy3.value);
			}
			

		//if(!validatePassword(document.getElementById('new_pass').value, 'NOPARAM')) 
		//{
			//alert('The password does not meets the required criteria. See footnote for details');
			//return false;
		//}
			
			
			
			
			
			if(document.frm_change.conformnewpassword.value=='' || document.frm_change.conformnewpassword.value== null)
			{
						document.getElementById('con-pass').innerHTML="Confirm Password should not be blank.";
						document.frm_change.conformnewpassword.focus();
						return false;
						
			}
		if(document.frm_change.conformnewpassword.value!='')
			{
				if(document.frm_change.conformnewpassword.value.length < 8)
					{
						document.getElementById('con-pass').innerHTML="Confirm password should contain 8 characters.";
						document.frm_change.conformnewpassword.focus();
						return false;
					}
					

			}
			if(document.frm_change.conformnewpassword.value!="")
				{
					//var encp=MD5(document.frm_change.conformnewpassword.value);
					//document.frm_change.conformnewpassword.value=mixUpValues(encp,document.frm_change.keyy2.value,document.frm_change.keyy3.value);
					document.getElementById('con-pass').innerHTML="";
					var hash = CryptoJS.HmacSHA256(document.frm_change.conformnewpassword.value, "");
					document.frm_change.conformnewpassword.value=mixUpValues(hash.toString(),document.frm_change.keyy2.value,document.frm_change.keyy3.value);
			
				}
			//password match
			if(document.frm_change.newpassword.value!='' && document.frm_change.newpassword.value!=''){
			//var com= StrComp(document.frm_change.new_pass.value , document.frm_change.new_pass.value)
				if(document.frm_change.newpassword.value != document.frm_change.conformnewpassword.value)
					{
						document.getElementById('con-pass').innerHTML="New Password and Confirm password does not matched.";
						//document.frm_change.confirm_pass.focus();
						return false;
				
					}
	if(jQuery('#vercode').val() == '')
		{
			document.getElementById('captcha-code').innerHTML="Captcha code <?php echo CANTEMPTY; ?>";
			jQuery( "#vercode" ).focus();
			return false;
		} 
		if(jQuery('#vercode').val() != ''){
			document.getElementById('captcha-code').innerHTML="";
		}
	}
	return true;		
}
	

</script>

<ol class="breadcrumb">
   <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
   <li><a href="<?php echo $this->baseUrl('user/userview'); ?>">User(s) List</a></li>
   <li class="active">Change Password</li>
</ol>
				
<?php
		$cmidata = $this->cmidata;
		$postUrlUpdate = $this->url(array('controller' => 'user','action'  => 'changeuserpassword'));
?>
			<form action="<?=$postUrlUpdate?>" method="post" name="frm_change" id="frm_change" onsubmit="return valPwd2();" class="changpass">
					<?php if($this->msg){?>
						<div class="col-sm-12 col-md-3"><span class="error"><?php echo $this->escape($this->msg); ?></span><div class="clearfix"></div></div>
					<?php }elseif($this->successMsg){
						echo "<div class='col-sm-12 col-md-3'><span class='success-msg'>".$this->successMsg."</span></div><div class='clearfix'></div>"; 
					}elseif($this->errorMessage){ ?>
						<div class="col-sm-12 col-md-3"><span class="error"><?php echo $this->escape($this->errorMessage); ?></span></div><div class="clearfix"></div>
					<?php } ?>
<div class="row">
						<div class="form-group col-xs-12 col-sm-6 col-md-4">
					<div class="row">
						<div class="form-group col-sm-12">
							<label>Old Password:<sup class="require">*</sup> </label>
							<?php echo $this->form->oldpassword?>
                            <span class="require" id="old-pass"></span>
							<input name="keyy" type="hidden" class="textbox" id="keyy" size="37" value="<?php echo time(); ?>"/>
							<input name="keyy1" type="hidden" class="textbox" id="keyy1" size="37" value="<?php echo mt_rand(10000,99999); ?>"/>
						</div>
						<div class="form-group col-sm-12">
							<label>New Password:<sup class="require">*</sup> </label>
							<?php echo $this->form->newpassword?>
                            <img data-toggle="tooltip" data-placement="left" data-html="true"  data-title=" Your password needs to:<br>
Atleast one lowercase character<br>
Atleast one uppercase character<br>
Atleast one digit<br>
Atleast one special sign of @#-_$%^&amp;+=§!?" src="../images/hint.png" alt="hint" class="hint" />
                           
                         
                            <span class="require" id="new-pass"></span>
							<input name="keyy2" type="hidden" class="textbox" id="keyy2" size="37" value="<?php echo time(); ?>"/>
							<input name="keyy3" type="hidden" class="textbox" id="keyy3" size="37" value="<?php echo mt_rand(10000,99999); ?>"/>
						</div>
						<div class="form-group col-sm-12">
							<label>Confirm Password:<sup class="require">*</sup> </label>
							<?php echo $this->form->conformnewpassword?>
                            <span class="require" id="con-pass"></span>
							
						</div>
							<!-----------Add Captcha Code Script----->
			 <div class="form-group col-sm-12 captcha-inner">
				<label>Captcha Code<sup class="require">*</sup>  </label>
                <?php echo $this->form->vercode; ?>
				<p><span>
					<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left"/></span>	
					<a  onclick="
						document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();
						document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>									
				</p>
				 <div class="clearfix"></div><span class="require" id="captcha-code"></span>
				<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
            </div>
           <!--------------End Captcha Code------->
						<div class="form-group col-md-12 col-sm-12 text-center">
							<button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="updateProfileButton">Change Password</button>
						</div>
					</div>
                    </div>
					</div>
			</form>

