<?php

 $userid = new Zend_Session_Namespace('userid');
        $admname = new Zend_Session_Namespace('adminMname');
	 $role = new Zend_Session_Namespace('role');
	// echo "ROLE=".$role->role;
	?>

<script type="text/javascript" language="javascript">
function valPwd2()
	{
		var iChars = "',\\\;&<>\"";
		var iChars1 = "',\\\;&<>\"~@#$%^*()_?><+_-|`:";
		var iChars_sec = "',\\\;&<>\"~@#$%^*()_><+_-|`:";
			/*********************************************************************************/
			if(document.frm_change.oldpassword.value=='' || document.frm_change.oldpassword.value == null)
			{
						alert("Old Password should not be blank.");
						document.frm_change.oldpassword.focus();
						return false;
						
			}

			if(document.frm_change.newpassword.value=='' || document.frm_change.newpassword.value== null)
			{
						alert("New Password should not be blank.");
						document.frm_change.newpassword.focus();
						return false;
						
			}

			

		/*************************************************************************************/

		if(document.frm_change.newpassword.value!='')
			{
				if(document.frm_change.newpassword.value.length < 8)
					{
						alert("New Password should contain 8 characters.");
						document.frm_change.newpassword.focus();
						return false;
					}
					
					for (var i = 0; i < document.frm_change.newpassword.value.length; i++) {
						if (iChars.indexOf(document.frm_change.newpassword.value.charAt(i)) != -1) {
							alert ("New Password field is either empty or contains space or disallowed character ( \' \\\ < > & , ; \"  ). Please correct and try again.");
							document.frm_change.newpassword.focus();
							return false;
						}
				  }
			}
			

		//if(!validatePassword(document.getElementById('new_pass').value, 'NOPARAM')) 
		//{
			//alert('The password does not meets the required criteria. See footnote for details');
			//return false;
		//}
			
			
			
			
			
			if(document.frm_change.conformnewpassword.value=='' || document.frm_change.conformnewpassword.value== null)
			{
						alert("Confirm Password should not be blank.");
						document.frm_change.conformnewpassword.focus();
						return false;
						
			}
		if(document.frm_change.conformnewpassword.value!='')
			{
				if(document.frm_change.conformnewpassword.value.length < 8)
					{
						alert("Confirm password should contain 8 characters.");
						document.frm_change.conformnewpassword.focus();
						return false;
					}
					

			}
			//password match
			if(document.frm_change.newpassword.value!='' && document.frm_change.newpassword.value!=''){
			//var com= StrComp(document.frm_change.new_pass.value , document.frm_change.new_pass.value)
				if(document.frm_change.newpassword.value != document.frm_change.conformnewpassword.value)
					{
						alert("New Password and Confirm password does not matched.");
						//document.frm_change.confirm_pass.focus();
						return false;
				
					}
			
			
			}
			
			return true;
			
	}
	

	
</script>
<!---
<ul class="tabs">

<?php if(($userid->userid)&&($role->role==1)){ ?>
                    <li><a href="<?php echo $this->url(array('controller' => 'user', 'action'  => 'userinfo')); ?>" title="<?php echo MY_ACCOUNT; ?>" class="active" ><?php echo MY_ACCOUNT; ?></a></li>

                    <li><a href="<?php echo $this->url(array('controller' => 'user', 'action'  => 'userview')); ?>" title="<?php echo MANAGE_USER ?>" ><?php echo MANAGE_USER; ?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'role', 'action'  => 'roleview')); ?>" title="<?php echo MANAGE_ROLE; ?>" ><?php echo MANAGE_ROLE; ?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'project', 'action'  => 'projectview')); ?>" title="<?php echo MANAGE_PROJECT ?>" ><?php echo MANAGE_PROJECT; ?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'location', 'action'  => 'locationview')); ?>" title="<?php echo MANAGE_LOCATION ?>" ><?php echo MANAGE_LOCATION; ?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'site', 'action'  => 'siteview')); ?>" title="<?php echo MANAGE_SITE; ?>" ><?php echo MANAGE_SITE; ?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'Assignmanager', 'action'  => 'index')); ?>" title="<?php echo ASSIGN_PROJECT; ?>" ><?php echo ASSIGN_PROJECT; ?></a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'Report', 'action'  => 'reportview')); ?>" title="<?php echo REPORT; ?>" ><?php echo REPORT; ?></a></li>
        <?php }elseif(($userid->userid)&&($role->role==2)){ ?>
		             <li><a href="<?php echo $this->url(array('controller' => 'user', 'action'  => 'userinfo')); ?>" title="<?php echo MY_ACCOUNT; ?>" class="active" ><?php echo MY_ACCOUNT; ?></a></li>

                    <li><a href="<?php echo $this->url(array('controller' => 'survey', 'action'  => 'show')); ?>" title="<?php echo SURVEY_PROJECT_LISTING; ?>" ><?php echo SURVEY_PROJECT_LISTING; ?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'survey', 'action'  => 'latestsurvey')); ?>" title="<?php echo SURVEY_UPDATE_HISTORY;?>"><?php echo SURVEY_UPDATE_HISTORY;?></a></li>	

        <?php }elseif(($userid->userid)&&($role->role==3)){ ?>

                        <li><a href="<?php echo $this->url(array('controller' => 'user', 'action'  => 'userinfo')); ?>" title="<?php echo MY_ACCOUNT; ?>" class="active" ><?php echo MY_ACCOUNT; ?></a></li>

                        <li><a href="<?php echo $this->url(array('controller' => 'customerproject', 'action'  => 'latestupdate')); ?>" title="<?php echo CUSTOMER_PROJECT_UPDATE ?>" ><?php echo CUSTOMER_PROJECT_UPDATE ?></a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'customerproject', 'action'  => 'customerprojectview')); ?>" title="<?php echo CUSTOMER_INSTALLATION_REPORT;?>"><?php echo CUSTOMER_INSTALLATION_REPORT; // this variable is defined in bootstrap.php?></a></li>

        <?php }elseif(($userid->userid)&&($role->role==4)){ ?>
		            <li><a href="<?php echo $this->url(array('controller' => 'user', 'action'  => 'userinfo')); ?>" title="<?php echo MY_ACCOUNT; ?>" class="active" ><?php echo MY_ACCOUNT; ?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'location', 'action'  => 'locationview')); ?>" title="<?php echo MANAGE_LOCATION;?>"><?php echo MANAGE_LOCATION;?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'site', 'action'  => 'siteview')); ?>" title="<?php echo MANAGE_SITE;?>"><?php echo MANAGE_SITE;?></a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'customer', 'action'  => 'assignengineer')); ?>" title="<?php echo MANAGE_ASSIGN_ENGINEER;?>"><?php echo MANAGE_ASSIGN_ENGINEER;?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action'  => 'assignsupervisior')); ?>" title="<?php echo MANAGE_TRANSFER_ENGINEER;?>"><?php echo MANAGE_TRANSFER_ENGINEER;?></a></li>
                    <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action'  => 'projectupdate')); ?>" title="<?php echo CUSTOMER_PROJECT_UPDATE;?>"><?php echo CUSTOMER_PROJECT_UPDATE;?></a></li>
					<li><a href="<?php echo $this->url(array('controller' => 'Report', 'action'  => 'reportview')); ?>" title="<?php echo REPORT; ?>" ><?php echo REPORT; ?></a></li>

        <?php } ?>					
</ul>
--->
<ol class="breadcrumb">
   <li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
   <li><a href="<?php echo $this->baseUrl('user/userview'); ?>">User(s) List</a></li>
   <li class="active">Reset</li>
</ol>	
<div class="cntnt">
<h2>Change Password</h2>
				
<?php
		 $cmidata = $this->cmidata;
		//$postUrlUpdate = $this->url(array('controller' => 'user',//'action'  => 'userview'))."?id=".$this->escape($cmidata['id']);
		$postUrlUpdate = $this->url(array('controller' => 'user',
		'action'  => 'changeuserpassword'));?>
<form action="<?=$postUrlUpdate?>" method="post" name="frm_change" id="frm_change" onsubmit="return valPwd2();" class="webform-client-form">
<?php 
    if($this->msg){
        echo "<div class='success-msg'>".$this->msg."</div>"; 
    }
?>
<div class="form-item">
						<label>Old Password:</label>
						<?=$this->form->oldpassword?>
					</div>
					<!--<div class="form-item">
						<label>Password:</label>
						<?=$this->form->password?>
					</div>-->
					<div class="form-item">
						<label>New Password:</label>
						<?=$this->form->newpassword?>
					</div>

					<div class="form-item">
						<label>Confirm Password:</label>
						<?=$this->form->conformnewpassword?>
					</div>
								
					<div  class="form-item">
						<input type="submit" class="mlft" value="Change Password" name="Submit" border="0"  />
						
					</div>
				</form>
			</div>







